/**
 * Shared i18n dictionary — ported from the kosova-ilan-mvp prototype.
 * 10 languages: Albanian, Serbian, Turkish, English, German, French, Italian, Bosnian, Greek, Russian.
 */

export type LangCode = 'sq' | 'sr' | 'tr' | 'en' | 'de' | 'fr' | 'it' | 'bs' | 'el' | 'ru';

export const LANGUAGES: { code: LangCode; name: string; flag: string }[] = [
  {code:'sq', name:'Shqip', flag:'🇦🇱'},
  {code:'sr', name:'Srpski', flag:'🇷🇸'},
  {code:'tr', name:'Türkçe', flag:'🇹🇷'},
  {code:'en', name:'English', flag:'🇬🇧'},
  {code:'de', name:'Deutsch', flag:'🇩🇪'},
  {code:'fr', name:'Français', flag:'🇫🇷'},
  {code:'it', name:'Italiano', flag:'🇮🇹'},
  {code:'bs', name:'Bosanski', flag:'🇧🇦'},
  {code:'el', name:'Ελληνικά', flag:'🇬🇷'},
  {code:'ru', name:'Русский', flag:'🇷🇺'}
];

export const DEFAULT_LANG: LangCode = 'tr';

export const UI = {
  hero_title: {sq:'Platforma e shpalljeve në Kosovë', sr:'Platforma oglasa na Kosovu', tr:'Kosova\'nın ilan platformu', en:'Kosovo\'s classifieds platform', de:'Kosovos Kleinanzeigen-Plattform', fr:'La plateforme de petites annonces du Kosovo', it:'La piattaforma di annunci del Kosovo', bs:'Platforma oglasa na Kosovu', el:'Η πλατφόρμα αγγελιών του Κοσόβου', ru:'Платформа объявлений Косово'},
  hero_subtitle: {sq:'Bleni dhe shisni prona, automjete dhe artikuj të përdorur me siguri.', sr:'Kupujte i prodajte nekretnine, vozila i polovnu robu bezbedno.', tr:'Emlak, vasıta ve ikinci el eşyayı güvenle alın, satın.', en:'Buy and sell real estate, vehicles and second-hand goods safely.', de:'Kaufen und verkaufen Sie sicher Immobilien, Fahrzeuge und Gebrauchtwaren.', fr:'Achetez et vendez en toute sécurité biens immobiliers, véhicules et articles d\'occasion.', it:'Compra e vendi immobili, veicoli e articoli usati in sicurezza.', bs:'Kupujte i prodajte nekretnine, vozila i polovnu robu sigurno.', el:'Αγοράστε και πουλήστε ακίνητα, οχήματα και μεταχειρισμένα είδη με ασφάλεια.', ru:'Покупайте и продавайте недвижимость, автомобили и товары с рук безопасно.'},
  search_placeholder: {sq:'Çfarë kërkoni? (p.sh. banesë Prishtinë)', sr:'Šta tražite? (npr. stan Priština)', tr:'Ne arıyorsunuz? (örn. Prishtina daire)', en:'What are you looking for? (e.g. apartment Prishtina)', de:'Wonach suchen Sie? (z.B. Wohnung Prishtina)', fr:'Que recherchez-vous ? (ex. appartement Pristina)', it:'Cosa stai cercando? (es. appartamento Pristina)', bs:'Šta tražite? (npr. stan Priština)', el:'Τι ψάχνετε; (π.χ. διαμέρισμα Πρίστινα)', ru:'Что вы ищете? (напр. квартира Приштина)'},
  search_button: {sq:'Kërko', sr:'Pretraga', tr:'Ara', en:'Search', de:'Suchen', fr:'Rechercher', it:'Cerca', bs:'Pretraga', el:'Αναζήτηση', ru:'Поиск'},
  nav_all: {sq:'Të gjitha', sr:'Sve', tr:'Tümü', en:'All', de:'Alle', fr:'Tous', it:'Tutti', bs:'Sve', el:'Όλα', ru:'Все'},
  login_button: {sq:'Hyr', sr:'Prijava', tr:'Giriş Yap', en:'Log In', de:'Anmelden', fr:'Connexion', it:'Accedi', bs:'Prijava', el:'Σύνδεση', ru:'Вход'},
  post_ad_button: {sq:'+ Posto Shpallje', sr:'+ Objavi Oglas', tr:'+ İlan Ver', en:'+ Post Ad', de:'+ Anzeige aufgeben', fr:'+ Publier une annonce', it:'+ Pubblica annuncio', bs:'+ Objavi Oglas', el:'+ Καταχώρηση Αγγελίας', ru:'+ Разместить объявление'},
  categories_title: {sq:'Kategoritë', sr:'Kategorije', tr:'Kategoriler', en:'Categories', de:'Kategorien', fr:'Catégories', it:'Categorie', bs:'Kategorije', el:'Κατηγορίες', ru:'Категории'},
  eyebrow_browse: {sq:'Eksploro', sr:'Istražite', tr:'Göz At', en:'Explore', de:'Entdecken', fr:'Explorer', it:'Esplora', bs:'Istražite', el:'Εξερευνήστε', ru:'Обзор'},
  eyebrow_listings: {sq:'Tregu', sr:'Tržište', tr:'Pazar Yeri', en:'Marketplace', de:'Marktplatz', fr:'Place de marché', it:'Mercato', bs:'Tržište', el:'Αγορά', ru:'Торговая площадка'},
  featured_title: {sq:'Shpalljet kryesore', sr:'Izdvojeni oglasi', tr:'Öne çıkan ilanlar', en:'Featured listings', de:'Empfohlene Anzeigen', fr:'Annonces à la une', it:'Annunci in evidenza', bs:'Izdvojeni oglasi', el:'Προτεινόμενες αγγελίες', ru:'Рекомендуемые объявления'},
  results_for: {sq:'Rezultatet për', sr:'Rezultati za', tr:'için sonuçlar', en:'Results for', de:'Ergebnisse für', fr:'Résultats pour', it:'Risultati per', bs:'Rezultati za', el:'Αποτελέσματα για', ru:'Результаты по запросу'},
  listing_count_suffix: {sq:'shpallje', sr:'oglasa', tr:'ilan', en:'listings', de:'Anzeigen', fr:'annonces', it:'annunci', bs:'oglasa', el:'αγγελίες', ru:'объявлений'},
  sort_default: {sq:'Renditja: Kryesore', sr:'Sortiranje: Izdvojeno', tr:'Sıralama: Öne çıkanlar', en:'Sort: Featured', de:'Sortierung: Empfohlen', fr:'Trier : À la une', it:'Ordina: In evidenza', bs:'Sortiranje: Izdvojeno', el:'Ταξινόμηση: Προτεινόμενα', ru:'Сортировка: Рекомендуемые'},
  sort_price_asc: {sq:'Çmimi: I ulët në të lartë', sr:'Cena: Od niže ka višoj', tr:'Fiyat: Ucuzdan Pahalıya', en:'Price: Low to High', de:'Preis: Aufsteigend', fr:'Prix : Croissant', it:'Prezzo: Crescente', bs:'Cijena: Od niže ka višoj', el:'Τιμή: Αύξουσα', ru:'Цена: По возрастанию'},
  sort_price_desc: {sq:'Çmimi: I lartë në të ulët', sr:'Cena: Od više ka nižoj', tr:'Fiyat: Pahalıdan Ucuza', en:'Price: High to Low', de:'Preis: Absteigend', fr:'Prix : Décroissant', it:'Prezzo: Decrescente', bs:'Cijena: Od više ka nižoj', el:'Τιμή: Φθίνουσα', ru:'Цена: По убыванию'},
  sort_nearest: {sq:'Më afër meje', sr:'Najbliže meni', tr:'Bana En Yakın', en:'Nearest to Me', de:'In meiner Nähe', fr:'Le plus proche', it:'Più vicino a me', bs:'Najbliže meni', el:'Πιο κοντά μου', ru:'Ближайшие ко мне'},
  filter_all_subcats: {sq:'Të gjitha nënkategoritë', sr:'Sve podkategorije', tr:'Tüm alt kategoriler', en:'All subcategories', de:'Alle Unterkategorien', fr:'Toutes les sous-catégories', it:'Tutte le sottocategorie', bs:'Sve podkategorije', el:'Όλες οι υποκατηγορίες', ru:'Все подкатегории'},
  filter_all_cities: {sq:'Të gjitha qytetet', sr:'Svi gradovi', tr:'Tüm şehirler', en:'All cities', de:'Alle Städte', fr:'Toutes les villes', it:'Tutte le città', bs:'Svi gradovi', el:'Όλες οι πόλεις', ru:'Все города'},
  filter_min_price: {sq:'Çmimi min €', sr:'Min cena €', tr:'Min fiyat €', en:'Min price €', de:'Min. Preis €', fr:'Prix min €', it:'Prezzo min €', bs:'Min cijena €', el:'Ελάχ. τιμή €', ru:'Мин. цена €'},
  filter_max_price: {sq:'Çmimi max €', sr:'Maks cena €', tr:'Max fiyat €', en:'Max price €', de:'Max. Preis €', fr:'Prix max €', it:'Prezzo max €', bs:'Maks cijena €', el:'Μέγ. τιμή €', ru:'Макс. цена €'},
  empty_results: {sq:'Nuk u gjet asnjë shpallje me këto kritere.', sr:'Nije pronađen nijedan oglas sa ovim kriterijumima.', tr:'Bu kriterlere uygun ilan bulunamadı.', en:'No listings found matching these criteria.', de:'Keine Anzeigen mit diesen Kriterien gefunden.', fr:'Aucune annonce trouvée avec ces critères.', it:'Nessun annuncio trovato con questi criteri.', bs:'Nije pronađen nijedan oglas sa ovim kriterijumima.', el:'Δεν βρέθηκαν αγγελίες με αυτά τα κριτήρια.', ru:'По этим критериям объявления не найдены.'},
  footer_text: {sq:'ShesBlej — platforma e shpalljeve të Kosovës.', sr:'ShesBlej — platforma oglasa Kosova.', tr:'ShesBlej — Kosova\'nın ilan platformu.', en:'ShesBlej — Kosovo\'s classifieds platform.', de:'ShesBlej — Kosovos Kleinanzeigenplattform.', fr:'ShesBlej — la plateforme de petites annonces du Kosovo.', it:'ShesBlej — la piattaforma di annunci del Kosovo.', bs:'ShesBlej — platforma oglasa Kosova.', el:'ShesBlej — η πλατφόρμα αγγελιών του Κοσσυφοπεδίου.', ru:'ShesBlej — платформа объявлений Косово.'},
  footer_terms_link: {sq:'Kushtet e Përdorimit', sr:'Uslovi Korišćenja', tr:'Kullanım Şartları', en:'Terms of Service', de:'Nutzungsbedingungen', fr:'Conditions d\'utilisation', it:'Termini di Servizio', bs:'Uslovi Korištenja', el:'Όροι Χρήσης', ru:'Условия использования'},
  footer_privacy_link: {sq:'Politika e Privatësisë', sr:'Politika Privatnosti', tr:'Gizlilik Politikası', en:'Privacy Policy', de:'Datenschutzerklärung', fr:'Politique de confidentialité', it:'Informativa sulla Privacy', bs:'Politika Privatnosti', el:'Πολιτική Απορρήτου', ru:'Политика конфиденциальности'},

  step_category: {sq:'Kategoria', sr:'Kategorija', tr:'Kategori', en:'Category', de:'Kategorie', fr:'Catégorie', it:'Categoria', bs:'Kategorija', el:'Κατηγορία', ru:'Категория'},
  step_details: {sq:'Detajet', sr:'Detalji', tr:'Detaylar', en:'Details', de:'Details', fr:'Détails', it:'Dettagli', bs:'Detalji', el:'Λεπτομέρειες', ru:'Детали'},
  step_location: {sq:'Vendndodhja', sr:'Lokacija', tr:'Konum', en:'Location', de:'Standort', fr:'Emplacement', it:'Posizione', bs:'Lokacija', el:'Τοποθεσία', ru:'Местоположение'},
  step_contact: {sq:'Kontakti', sr:'Kontakt', tr:'İletişim', en:'Contact', de:'Kontakt', fr:'Contact', it:'Contatto', bs:'Kontakt', el:'Επικοινωνία', ru:'Контакты'},

  post_ad_title: {sq:'Posto Shpallje të Re', sr:'Objavi Novi Oglas', tr:'Yeni İlan Ver', en:'Post a New Ad', de:'Neue Anzeige aufgeben', fr:'Publier une nouvelle annonce', it:'Pubblica un nuovo annuncio', bs:'Objavi Novi Oglas', el:'Καταχώρηση Νέας Αγγελίας', ru:'Разместить новое объявление'},
  label_category: {sq:'Kategoria', sr:'Kategorija', tr:'Kategori', en:'Category', de:'Kategorie', fr:'Catégorie', it:'Categoria', bs:'Kategorija', el:'Κατηγορία', ru:'Категория'},
  label_subcategory: {sq:'Nënkategoria', sr:'Podkategorija', tr:'Alt Kategori', en:'Subcategory', de:'Unterkategorie', fr:'Sous-catégorie', it:'Sottocategoria', bs:'Podkategorija', el:'Υποκατηγορία', ru:'Подкатегория'},
  label_title: {sq:'Titulli', sr:'Naslov', tr:'Başlık', en:'Title', de:'Titel', fr:'Titre', it:'Titolo', bs:'Naslov', el:'Τίτλος', ru:'Заголовок'},
  placeholder_title: {sq:'p.sh. Banesë 2+1 në shitje, Prishtinë', sr:'npr. Stan 2+1 na prodaju, Priština', tr:'örn. 2+1 Satılık Daire, Prishtina', en:'e.g. 2-bed apartment for sale, Prishtina', de:'z.B. 2-Zimmer-Wohnung zu verkaufen, Prishtina', fr:'ex. Appartement 2 pièces à vendre, Pristina', it:'es. Appartamento 2 stanze in vendita, Pristina', bs:'npr. Stan 2+1 na prodaju, Priština', el:'π.χ. Διαμέρισμα 2 δωμ. προς πώληση, Πρίστινα', ru:'напр. Продаётся 2-комн. квартира, Приштина'},
  label_price: {sq:'Çmimi (€)', sr:'Cena (€)', tr:'Fiyat (€)', en:'Price (€)', de:'Preis (€)', fr:'Prix (€)', it:'Prezzo (€)', bs:'Cijena (€)', el:'Τιμή (€)', ru:'Цена (€)'},
  placeholder_price: {sq:'p.sh. 45000', sr:'npr. 45000', tr:'örn. 45000', en:'e.g. 45000', de:'z.B. 45000', fr:'ex. 45000', it:'es. 45000', bs:'npr. 45000', el:'π.χ. 45000', ru:'напр. 45000'},
  label_description: {sq:'Përshkrimi', sr:'Opis', tr:'Açıklama', en:'Description', de:'Beschreibung', fr:'Description', it:'Descrizione', bs:'Opis', el:'Περιγραφή', ru:'Описание'},
  placeholder_description: {sq:'Shkruani detajet e shpalljes...', sr:'Unesite detalje oglasa...', tr:'İlan detaylarını yazın...', en:'Write the ad details...', de:'Anzeigendetails eingeben...', fr:'Rédigez les détails de l\'annonce...', it:'Scrivi i dettagli dell\'annuncio...', bs:'Unesite detalje oglasa...', el:'Γράψτε τις λεπτομέρειες...', ru:'Опишите объявление...'},
  label_city: {sq:'Qyteti', sr:'Grad', tr:'Şehir', en:'City', de:'Stadt', fr:'Ville', it:'Città', bs:'Grad', el:'Πόλη', ru:'Город'},
  label_district: {sq:'Lagjja', sr:'Naselje', tr:'Semt / Mahalle', en:'District', de:'Stadtteil', fr:'Quartier', it:'Quartiere', bs:'Naselje', el:'Συνοικία', ru:'Район'},
  placeholder_district: {sq:'p.sh. Bregu i Diellit', sr:'npr. Bregu i Diellit', tr:'örn. Bregu i Diellit', en:'e.g. Bregu i Diellit', de:'z.B. Bregu i Diellit', fr:'ex. Bregu i Diellit', it:'es. Bregu i Diellit', bs:'npr. Bregu i Diellit', el:'π.χ. Bregu i Diellit', ru:'напр. Bregu i Diellit'},
  label_map: {sq:'Shënoni vendndodhjen në hartë', sr:'Označite lokaciju na mapi', tr:'Haritada Konum İşaretleyin', en:'Mark location on map', de:'Standort auf der Karte markieren', fr:'Indiquer l\'emplacement sur la carte', it:'Segna la posizione sulla mappa', bs:'Označite lokaciju na mapi', el:'Σημειώστε την τοποθεσία στον χάρτη', ru:'Отметьте местоположение на карте'},
  map_hint: {sq:'Klikoni në hartë për të shënuar vendndodhjen', sr:'Kliknite na mapu da označite lokaciju', tr:'Konumu işaretlemek için haritaya tıklayın', en:'Click the map to mark the location', de:'Klicken Sie auf die Karte, um den Standort zu markieren', fr:'Cliquez sur la carte pour indiquer l\'emplacement', it:'Clicca sulla mappa per segnare la posizione', bs:'Kliknite na mapu da označite lokaciju', el:'Κάντε κλικ στον χάρτη για να σημειώσετε την τοποθεσία', ru:'Нажмите на карту, чтобы отметить местоположение'},
  map_status_ok: {sq:'Vendndodhja u shënua ✓', sr:'Lokacija označena ✓', tr:'Konum işaretlendi ✓', en:'Location marked ✓', de:'Standort markiert ✓', fr:'Emplacement indiqué ✓', it:'Posizione segnata ✓', bs:'Lokacija označena ✓', el:'Η τοποθεσία σημειώθηκε ✓', ru:'Местоположение отмечено ✓'},
  location_hint_required: {sq:'Për shpalljet e pronave, qyteti, lagjja dhe vendndodhja në hartë janë të detyrueshme.', sr:'Za oglase nekretnina, grad, naselje i lokacija na mapi su obavezni.', tr:'Emlak ilanlarında şehir, semt ve harita konumu zorunludur.', en:'For real estate listings, city, district and map location are required.', de:'Bei Immobilienanzeigen sind Stadt, Stadtteil und Kartenstandort erforderlich.', fr:'Pour les annonces immobilières, la ville, le quartier et l\'emplacement sur la carte sont obligatoires.', it:'Per gli annunci immobiliari, città, quartiere e posizione sulla mappa sono obbligatori.', bs:'Za oglase nekretnina, grad, naselje i lokacija na mapi su obavezni.', el:'Για αγγελίες ακινήτων, η πόλη, η συνοικία και η τοποθεσία στον χάρτη είναι υποχρεωτικά.', ru:'Для объявлений о недвижимости обязательны город, район и местоположение на карте.'},
  location_hint_optional: {sq:'Në këtë kategori vetëm qyteti është i detyrueshëm; lagjja dhe harta janë opsionale.', sr:'U ovoj kategoriji samo je grad obavezan; naselje i mapa su opcioni.', tr:'Bu kategoride yalnızca şehir seçimi zorunludur; semt ve harita konumu isteğe bağlıdır.', en:'In this category only the city is required; district and map are optional.', de:'In dieser Kategorie ist nur die Stadt erforderlich; Stadtteil und Karte sind optional.', fr:'Dans cette catégorie, seule la ville est obligatoire ; le quartier et la carte sont facultatifs.', it:'In questa categoria è obbligatoria solo la città; quartiere e mappa sono facoltativi.', bs:'U ovoj kategoriji samo je grad obavezan; naselje i mapa su opcioni.', el:'Σε αυτή την κατηγορία απαιτείται μόνο η πόλη· η συνοικία και ο χάρτης είναι προαιρετικά.', ru:'В этой категории обязателен только город; район и карта необязательны.'},
  label_phone: {sq:'Telefoni', sr:'Telefon', tr:'Telefon', en:'Phone', de:'Telefon', fr:'Téléphone', it:'Telefono', bs:'Telefon', el:'Τηλέφωνο', ru:'Телефон'},
  btn_back: {sq:'Prapa', sr:'Nazad', tr:'Geri', en:'Back', de:'Zurück', fr:'Retour', it:'Indietro', bs:'Nazad', el:'Πίσω', ru:'Назад'},
  btn_next: {sq:'Vazhdo', sr:'Dalje', tr:'İleri', en:'Next', de:'Weiter', fr:'Suivant', it:'Avanti', bs:'Dalje', el:'Επόμενο', ru:'Далее'},
  btn_publish: {sq:'Publiko Shpalljen', sr:'Objavi Oglas', tr:'İlanı Yayınla', en:'Publish Ad', de:'Anzeige veröffentlichen', fr:'Publier l\'annonce', it:'Pubblica annuncio', bs:'Objavi Oglas', el:'Δημοσίευση Αγγελίας', ru:'Опубликовать объявление'},

  toast_fill_title_price: {sq:'Ju lutemi plotësoni titullin dhe çmimin.', sr:'Molimo popunite naslov i cenu.', tr:'Lütfen başlık ve fiyat girin.', en:'Please fill in the title and price.', de:'Bitte Titel und Preis eingeben.', fr:'Veuillez saisir le titre et le prix.', it:'Inserisci titolo e prezzo.', bs:'Molimo popunite naslov i cijenu.', el:'Συμπληρώστε τον τίτλο και την τιμή.', ru:'Укажите заголовок и цену.'},
  toast_district_required: {sq:'Lagjja është e detyrueshme për shpalljet e pronave.', sr:'Naselje je obavezno za oglase nekretnina.', tr:'Emlak ilanlarında semt/mahalle zorunludur.', en:'District is required for real estate listings.', de:'Bei Immobilienanzeigen ist der Stadtteil erforderlich.', fr:'Le quartier est obligatoire pour les annonces immobilières.', it:'Il quartiere è obbligatorio per gli annunci immobiliari.', bs:'Naselje je obavezno za oglase nekretnina.', el:'Η συνοικία είναι υποχρεωτική για αγγελίες ακινήτων.', ru:'Для объявлений о недвижимости район обязателен.'},
  toast_map_required: {sq:'Ju lutemi shënoni vendndodhjen në hartë.', sr:'Molimo označite lokaciju na mapi.', tr:'Lütfen haritada konumu işaretleyin.', en:'Please mark the location on the map.', de:'Bitte markieren Sie den Standort auf der Karte.', fr:'Veuillez indiquer l\'emplacement sur la carte.', it:'Segna la posizione sulla mappa.', bs:'Molimo označite lokaciju na mapi.', el:'Σημειώστε την τοποθεσία στον χάρτη.', ru:'Отметьте местоположение на карте.'},
  toast_phone_required: {sq:'Numri i telefonit është i detyrueshëm.', sr:'Broj telefona je obavezan.', tr:'Telefon numarası zorunludur.', en:'Phone number is required.', de:'Telefonnummer ist erforderlich.', fr:'Le numéro de téléphone est obligatoire.', it:'Il numero di telefono è obbligatorio.', bs:'Broj telefona je obavezan.', el:'Ο αριθμός τηλεφώνου είναι υποχρεωτικός.', ru:'Требуется номер телефона.'},
  toast_ad_published: {sq:'Shpallja juaj u publikua me sukses!', sr:'Vaš oglas je uspešno objavljen!', tr:'İlanınız başarıyla yayınlandı!', en:'Your ad was published successfully!', de:'Ihre Anzeige wurde erfolgreich veröffentlicht!', fr:'Votre annonce a été publiée avec succès !', it:'Il tuo annuncio è stato pubblicato con successo!', bs:'Vaš oglas je uspešno objavljen!', el:'Η αγγελία σας δημοσιεύτηκε με επιτυχία!', ru:'Ваше объявление успешно опубликовано!'},

  login_title: {sq:'Hyr', sr:'Prijava', tr:'Giriş Yap', en:'Log In', de:'Anmelden', fr:'Connexion', it:'Accedi', bs:'Prijava', el:'Σύνδεση', ru:'Вход'},
  register_title: {sq:'Regjistrohu', sr:'Registracija', tr:'Kayıt Ol', en:'Register', de:'Registrieren', fr:'Inscription', it:'Registrati', bs:'Registracija', el:'Εγγραφή', ru:'Регистрация'},
  auth_demo_note: {sq:'Ky është një prototip — nuk përfshin vërtetim real, vetëm demonstron rrjedhën.', sr:'Ovo je prototip — ne sadrži pravu autentikaciju, samo demonstrira tok.', tr:'Bu bir prototip — gerçek kimlik doğrulama içermez, yalnızca akışı gösterir.', en:'This is a prototype — it has no real authentication, it only demonstrates the flow.', de:'Dies ist ein Prototyp — keine echte Authentifizierung, zeigt nur den Ablauf.', fr:'Ceci est un prototype — sans authentification réelle, il illustre seulement le parcours.', it:'Questo è un prototipo — senza autenticazione reale, mostra solo il flusso.', bs:'Ovo je prototip — ne sadrži pravu autentikaciju, samo demonstrira tok.', el:'Αυτό είναι πρωτότυπο — χωρίς πραγματική πιστοποίηση, δείχνει μόνο τη ροή.', ru:'Это прототип — без настоящей аутентификации, только демонстрация процесса.'},
  label_fullname: {sq:'Emri dhe Mbiemri', sr:'Ime i Prezime', tr:'Ad Soyad', en:'Full Name', de:'Vollständiger Name', fr:'Nom complet', it:'Nome completo', bs:'Ime i Prezime', el:'Ονοματεπώνυμο', ru:'Полное имя'},
  label_email: {sq:'E-mail', sr:'E-mail', tr:'E-posta', en:'Email', de:'E-Mail', fr:'E-mail', it:'Email', bs:'E-mail', el:'Email', ru:'Эл. почта'},
  label_password: {sq:'Fjalëkalimi', sr:'Lozinka', tr:'Şifre', en:'Password', de:'Passwort', fr:'Mot de passe', it:'Password', bs:'Lozinka', el:'Κωδικός', ru:'Пароль'},
  label_password_confirm: {sq:'Përsërit Fjalëkalimin', sr:'Ponovi Lozinku', tr:'Şifre Tekrar', en:'Confirm Password', de:'Passwort bestätigen', fr:'Confirmer le mot de passe', it:'Conferma password', bs:'Ponovi Lozinku', el:'Επιβεβαίωση Κωδικού', ru:'Повторите пароль'},
  label_phone_optional: {sq:'Telefoni (opsionale)', sr:'Telefon (opciono)', tr:'Telefon (opsiyonel)', en:'Phone (optional)', de:'Telefon (optional)', fr:'Téléphone (facultatif)', it:'Telefono (facoltativo)', bs:'Telefon (opciono)', el:'Τηλέφωνο (προαιρετικό)', ru:'Телефон (необязательно)'},
  label_id_number: {sq:'Numri Personal / ID', sr:'JMBG / Lični Broj', tr:'Kimlik Numarası', en:'National ID Number', de:'Ausweisnummer', fr:'Numéro de pièce d\'identité', it:'Numero documento d\'identità', bs:'JMBG / Lični Broj', el:'Αριθμός Ταυτότητας', ru:'Номер удостоверения личности'},
  label_birth_date: {sq:'Datëlindja', sr:'Datum Rođenja', tr:'Doğum Tarihi', en:'Date of Birth', de:'Geburtsdatum', fr:'Date de naissance', it:'Data di nascita', bs:'Datum Rođenja', el:'Ημερομηνία Γέννησης', ru:'Дата рождения'},
  label_consent: {sq:'Pranoj që të dhënat e mia personale (përfshirë ID-në dhe datëlindjen) të përpunohen sipas ligjit për mbrojtjen e të dhënave në fuqi, me qëllim verifikimin e identitetit dhe parandalimin e mashtrimit.', sr:'Prihvatam da se moji lični podaci (uključujući ID broj i datum rođenja) obrađuju u skladu sa važećim zakonom o zaštiti podataka, u svrhu verifikacije identiteta i sprečavanja prevare.', tr:'Kişisel verilerimin (kimlik numarası ve doğum tarihi dahil) yürürlükteki veri koruma mevzuatına uygun şekilde, kimlik doğrulama ve dolandırıcılığın önlenmesi amacıyla işlenmesini kabul ediyorum.', en:'I agree that my personal data (including ID number and date of birth) will be processed in accordance with applicable data protection law, for identity verification and fraud prevention purposes.', de:'Ich stimme zu, dass meine personenbezogenen Daten (einschließlich Ausweisnummer und Geburtsdatum) gemäß geltendem Datenschutzrecht zur Identitätsprüfung und Betrugsprävention verarbeitet werden.', fr:'J\'accepte que mes données personnelles (y compris le numéro d\'identité et la date de naissance) soient traitées conformément à la loi applicable sur la protection des données, à des fins de vérification d\'identité et de prévention de la fraude.', it:'Accetto che i miei dati personali (compreso il numero di documento e la data di nascita) siano trattati in conformità con la legge sulla protezione dei dati applicabile, per la verifica dell\'identità e la prevenzione delle frodi.', bs:'Prihvatam da se moji lični podaci (uključujući ID broj i datum rođenja) obrađuju u skladu sa važećim zakonom o zaštiti podataka, u svrhu verifikacije identiteta i sprečavanja prevare.', el:'Συμφωνώ τα προσωπικά μου δεδομένα (συμπεριλαμβανομένου του αριθμού ταυτότητας και της ημερομηνίας γέννησης) να υποβάλλονται σε επεξεργασία σύμφωνα με την ισχύουσα νομοθεσία προστασίας δεδομένων, για σκοπούς επαλήθευσης ταυτότητας και πρόληψης απάτης.', ru:'Я согласен(на) на обработку моих персональных данных (включая номер удостоверения личности и дату рождения) в соответствии с действующим законодательством о защите данных в целях проверки личности и предотвращения мошенничества.'},
  toast_consent_required: {sq:'Duhet të pranoni përpunimin e të dhënave personale për t\'u regjistruar.', sr:'Morate prihvatiti obradu ličnih podataka da biste se registrovali.', tr:'Kayıt olmak için kişisel veri işleme iznini onaylamalısınız.', en:'You must accept personal data processing to register.', de:'Sie müssen der Verarbeitung personenbezogener Daten zustimmen, um sich zu registrieren.', fr:'Vous devez accepter le traitement des données personnelles pour vous inscrire.', it:'Devi accettare il trattamento dei dati personali per registrarti.', bs:'Morate prihvatiti obradu ličnih podataka da biste se registrovali.', el:'Πρέπει να αποδεχτείτε την επεξεργασία προσωπικών δεδομένων για εγγραφή.', ru:'Для регистрации необходимо согласиться на обработку персональных данных.'},
  btn_login: {sq:'Hyr', sr:'Prijavi se', tr:'Giriş Yap', en:'Log In', de:'Anmelden', fr:'Se connecter', it:'Accedi', bs:'Prijavi se', el:'Σύνδεση', ru:'Войти'},
  btn_register: {sq:'Regjistrohu', sr:'Registruj se', tr:'Kayıt Ol', en:'Register', de:'Registrieren', fr:'S\'inscrire', it:'Registrati', bs:'Registruj se', el:'Εγγραφή', ru:'Зарегистрироваться'},
  switch_to_register: {sq:'Nuk keni llogari? Regjistrohuni', sr:'Nemate nalog? Registrujte se', tr:'Hesabınız yok mu? Kayıt Olun', en:'Don\'t have an account? Register', de:'Kein Konto? Registrieren', fr:'Pas de compte ? Inscrivez-vous', it:'Non hai un account? Registrati', bs:'Nemate nalog? Registrujte se', el:'Δεν έχετε λογαριασμό; Εγγραφείτε', ru:'Нет аккаунта? Зарегистрируйтесь'},
  switch_to_login: {sq:'Keni tashmë llogari? Hyni', sr:'Već imate nalog? Prijavite se', tr:'Zaten hesabınız var mı? Giriş Yapın', en:'Already have an account? Log in', de:'Bereits ein Konto? Anmelden', fr:'Déjà un compte ? Connectez-vous', it:'Hai già un account? Accedi', bs:'Već imate nalog? Prijavite se', el:'Έχετε ήδη λογαριασμό; Συνδεθείτε', ru:'Уже есть аккаунт? Войдите'},
  toast_welcome: {sq:'Mirë se erdhët', sr:'Dobrodošli', tr:'Hoş geldiniz', en:'Welcome', de:'Willkommen', fr:'Bienvenue', it:'Benvenuto/a', bs:'Dobrodošli', el:'Καλώς ήρθατε', ru:'Добро пожаловать'},
  toast_user_not_found: {sq:'Nuk u gjet përdorues me këtë email. Ju lutemi regjistrohuni.', sr:'Korisnik sa ovim email-om nije pronađen. Molimo registrujte se.', tr:'Bu e-posta ile kayıtlı kullanıcı bulunamadı. Lütfen kayıt olun.', en:'No user found with this email. Please register.', de:'Kein Benutzer mit dieser E-Mail gefunden. Bitte registrieren.', fr:'Aucun utilisateur trouvé avec cet e-mail. Veuillez vous inscrire.', it:'Nessun utente trovato con questa email. Registrati.', bs:'Korisnik sa ovim email-om nije pronađen. Molimo registrujte se.', el:'Δεν βρέθηκε χρήστης με αυτό το email. Παρακαλώ εγγραφείτε.', ru:'Пользователь с такой почтой не найден. Пожалуйста, зарегистрируйтесь.'},
  toast_passwords_mismatch: {sq:'Fjalëkalimet nuk përputhen.', sr:'Lozinke se ne podudaraju.', tr:'Şifreler eşleşmiyor.', en:'Passwords do not match.', de:'Passwörter stimmen nicht überein.', fr:'Les mots de passe ne correspondent pas.', it:'Le password non corrispondono.', bs:'Lozinke se ne podudaraju.', el:'Οι κωδικοί δεν ταιριάζουν.', ru:'Пароли не совпадают.'},
  toast_password_short: {sq:'Fjalëkalimi duhet të ketë të paktën 6 karaktere.', sr:'Lozinka mora imati najmanje 6 karaktera.', tr:'Şifre en az 6 karakter olmalıdır.', en:'Password must be at least 6 characters.', de:'Das Passwort muss mindestens 6 Zeichen lang sein.', fr:'Le mot de passe doit contenir au moins 6 caractères.', it:'La password deve contenere almeno 6 caratteri.', bs:'Lozinka mora imati najmanje 6 karaktera.', el:'Ο κωδικός πρέπει να έχει τουλάχιστον 6 χαρακτήρες.', ru:'Пароль должен содержать не менее 6 символов.'},
  toast_fill_required: {sq:'Ju lutemi plotësoni fushat e detyrueshme.', sr:'Molimo popunite obavezna polja.', tr:'Lütfen zorunlu alanları doldurun.', en:'Please fill in the required fields.', de:'Bitte füllen Sie die Pflichtfelder aus.', fr:'Veuillez remplir les champs obligatoires.', it:'Compila i campi obbligatori.', bs:'Molimo popunite obavezna polja.', el:'Συμπληρώστε τα υποχρεωτικά πεδία.', ru:'Заполните обязательные поля.'},
  toast_already_registered: {sq:'Ky email është regjistruar tashmë. Ju lutemi hyni.', sr:'Ovaj email je već registrovan. Molimo prijavite se.', tr:'Bu e-posta zaten kayıtlı. Lütfen giriş yapın.', en:'This email is already registered. Please log in.', de:'Diese E-Mail ist bereits registriert. Bitte anmelden.', fr:'Cet e-mail est déjà enregistré. Veuillez vous connecter.', it:'Questa email è già registrata. Accedi.', bs:'Ovaj email je već registrovan. Molimo prijavite se.', el:'Αυτό το email είναι ήδη καταχωρημένο. Παρακαλώ συνδεθείτε.', ru:'Эта почта уже зарегистрирована. Пожалуйста, войдите.'},

  detail_contact_label: {sq:'Kontakti', sr:'Kontakt', tr:'İletişim', en:'Contact', de:'Kontakt', fr:'Contact', it:'Contatto', bs:'Kontakt', el:'Επικοινωνία', ru:'Контакты'},
  detail_phone_label: {sq:'Telefoni', sr:'Telefon', tr:'Telefon', en:'Phone', de:'Telefon', fr:'Téléphone', it:'Telefono', bs:'Telefon', el:'Τηλέφωνο', ru:'Телефон'},
  detail_demo_note: {sq:'Shënim: ky prototip nuk ka sistem real mesazhesh.', sr:'Napomena: ovaj prototip nema pravi sistem poruka.', tr:'Not: bu prototipte gerçek mesajlaşma sistemi yoktur.', en:'Note: this prototype has no real messaging system.', de:'Hinweis: Dieser Prototyp hat kein echtes Nachrichtensystem.', fr:'Remarque : ce prototype n\'a pas de vrai système de messagerie.', it:'Nota: questo prototipo non ha un vero sistema di messaggistica.', bs:'Napomena: ovaj prototip nema pravi sistem poruka.', el:'Σημείωση: αυτό το πρωτότυπο δεν έχει πραγματικό σύστημα μηνυμάτων.', ru:'Примечание: в этом прототипе нет настоящей системы сообщений.'},
  marked_on_map: {sq:'Vendndodhje e shënuar në hartë', sr:'Lokacija označena na mapi', tr:'Haritada işaretli konum', en:'Location marked on map', de:'Standort auf Karte markiert', fr:'Emplacement indiqué sur la carte', it:'Posizione segnata sulla mappa', bs:'Lokacija označena na mapi', el:'Τοποθεσία σημειωμένη στον χάρτη', ru:'Местоположение отмечено на карте'},
  days_left_word: {sq:'ditë të mbetura', sr:'dana preostalo', tr:'gün kaldı', en:'days left', de:'Tage übrig', fr:'jours restants', it:'giorni rimasti', bs:'dana preostalo', el:'ημέρες απομένουν', ru:'дней осталось'},
  detail_expiry_suffix: {sq:'ditë deri sa shpallja të hiqet automatikisht', sr:'dana do automatskog uklanjanja oglasa', tr:'gün sonra ilan otomatik olarak kaldırılacak', en:'days until this listing is automatically removed', de:'Tage, bis die Anzeige automatisch entfernt wird', fr:'jours avant la suppression automatique de l\'annonce', it:'giorni prima che l\'annuncio venga rimosso automaticamente', bs:'dana do automatskog uklanjanja oglasa', el:'ημέρες μέχρι την αυτόματη αφαίρεση της αγγελίας', ru:'дней до автоматического удаления объявления'},
  post_ad_expiry_hint: {sq:'Shpallja juaj do të qëndrojë aktive për 29 ditë dhe do të hiqet automatikisht pas kësaj periudhe.', sr:'Vaš oglas će biti aktivan 29 dana i biće automatski uklonjen nakon tog perioda.', tr:'İlanınız yayınlandıktan sonra 29 gün boyunca aktif kalacak ve süre sonunda otomatik olarak kaldırılacaktır.', en:'Your ad will stay active for 29 days and will be automatically removed after that period.', de:'Ihre Anzeige bleibt 29 Tage aktiv und wird danach automatisch entfernt.', fr:'Votre annonce restera active pendant 29 jours puis sera automatiquement supprimée.', it:'Il tuo annuncio rimarrà attivo per 29 giorni e verrà rimosso automaticamente al termine di questo periodo.', bs:'Vaš oglas će biti aktivan 29 dana i biće automatski uklonjen nakon tog perioda.', el:'Η αγγελία σας θα παραμείνει ενεργή για 29 ημέρες και θα αφαιρεθεί αυτόματα μετά από αυτό το διάστημα.', ru:'Ваше объявление будет активно 29 дней, после чего будет автоматически удалено.'},

  admin_panel_link: {sq:'Paneli i Administratorit', sr:'Administratorski Panel', tr:'Yönetici Paneli', en:'Admin Panel', de:'Admin-Bereich', fr:'Panneau admin', it:'Pannello admin', bs:'Administratorski Panel', el:'Πίνακας Διαχείρισης', ru:'Панель администратора'},
  admin_panel_title: {sq:'Anëtarët e Regjistruar', sr:'Registrovani Članovi', tr:'Kayıtlı Üyeler', en:'Registered Members', de:'Registrierte Mitglieder', fr:'Membres inscrits', it:'Membri registrati', bs:'Registrovani Članovi', el:'Εγγεγραμμένα Μέλη', ru:'Зарегистрированные пользователи'},
  admin_panel_note: {sq:'Këto të dhëna ruhen vetëm në këtë shfletues (localStorage) — nuk ka ende server real. Për regjistrime nga të gjitha pajisjet duhet një bazë të dhënash reale.', sr:'Ovi podaci se čuvaju samo u ovom pregledaču (localStorage) — još nema pravog servera. Za registracije sa svih uređaja potrebna je prava baza podataka.', tr:'Bu veriler yalnızca bu tarayıcıda (localStorage) saklanıyor — henüz gerçek bir sunucu yok. Tüm cihazlardan gelen kayıtları görmek için gerçek bir veritabanı gerekir.', en:'This data is stored only in this browser (localStorage) — there is no real server yet. Seeing registrations from all devices requires a real database.', de:'Diese Daten werden nur in diesem Browser gespeichert (localStorage) — es gibt noch keinen echten Server. Für Registrierungen von allen Geräten ist eine echte Datenbank erforderlich.', fr:'Ces données sont stockées uniquement dans ce navigateur (localStorage) — il n\'y a pas encore de vrai serveur. Voir les inscriptions de tous les appareils nécessite une vraie base de données.', it:'Questi dati sono salvati solo in questo browser (localStorage) — non c\'è ancora un vero server. Per vedere le registrazioni da tutti i dispositivi serve un vero database.', bs:'Ovi podaci se čuvaju samo u ovom pregledaču (localStorage) — još nema pravog servera. Za registracije sa svih uređaja potrebna je prava baza podataka.', el:'Αυτά τα δεδομένα αποθηκεύονται μόνο σε αυτό το πρόγραμμα περιήγησης (localStorage) — δεν υπάρχει ακόμη πραγματικός διακομιστής. Για εγγραφές από όλες τις συσκευές απαιτείται πραγματική βάση δεδομένων.', ru:'Эти данные хранятся только в этом браузере (localStorage) — настоящего сервера пока нет. Чтобы видеть регистрации со всех устройств, нужна настоящая база данных.'},
  admin_no_users: {sq:'Ende asnjë anëtar i regjistruar.', sr:'Još uvek nema registrovanih članova.', tr:'Henüz kayıtlı üye yok.', en:'No registered members yet.', de:'Noch keine registrierten Mitglieder.', fr:'Aucun membre inscrit pour l\'instant.', it:'Nessun membro registrato ancora.', bs:'Još uvijek nema registrovanih članova.', el:'Δεν υπάρχουν ακόμη εγγεγραμμένα μέλη.', ru:'Пока нет зарегистрированных пользователей.'},
  admin_col_name: {sq:'Emri', sr:'Ime', tr:'Ad Soyad', en:'Name', de:'Name', fr:'Nom', it:'Nome', bs:'Ime', el:'Όνομα', ru:'Имя'},
  admin_col_email: {sq:'E-mail', sr:'E-mail', tr:'E-posta', en:'Email', de:'E-Mail', fr:'E-mail', it:'Email', bs:'E-mail', el:'Email', ru:'Эл. почта'},
  admin_col_phone: {sq:'Telefoni', sr:'Telefon', tr:'Telefon', en:'Phone', de:'Telefon', fr:'Téléphone', it:'Telefono', bs:'Telefon', el:'Τηλέφωνο', ru:'Телефон'},
  admin_col_date: {sq:'Regjistruar', sr:'Registrovan', tr:'Kayıt Tarihi', en:'Registered', de:'Registriert', fr:'Inscrit le', it:'Registrato', bs:'Registrovan', el:'Εγγραφή', ru:'Дата регистрации'},
  admin_col_id_number: {sq:'ID', sr:'Lični Broj', tr:'Kimlik No', en:'ID Number', de:'Ausweis-Nr.', fr:'N° ID', it:'N. documento', bs:'Lični Broj', el:'Αρ. Ταυτότητας', ru:'№ удостоверения'},
  admin_col_birth_date: {sq:'Datëlindja', sr:'Datum Rođenja', tr:'Doğum Tarihi', en:'Date of Birth', de:'Geburtsdatum', fr:'Naissance', it:'Data di nascita', bs:'Datum Rođenja', el:'Γέννηση', ru:'Дата рождения'},
  admin_col_consent: {sq:'Pëlqimi', sr:'Saglasnost', tr:'Onay', en:'Consent', de:'Einwilligung', fr:'Consentement', it:'Consenso', bs:'Saglasnost', el:'Συναίνεση', ru:'Согласие'},
  admin_security_warning: {sq:'⚠️ Këto janë të dhëna shumë të ndjeshme (ID, datëlindje). Ky prototip i ruan pa enkriptim në shfletues — para nisjes reale duhet enkriptim, bazë ligjore e rishikuar dhe backend i sigurt.', sr:'⚠️ Ovo su veoma osetljivi podaci (ID, datum rođenja). Ovaj prototip ih čuva bez enkripcije u pregledaču — pre pravog lansiranja potrebna je enkripcija, pravni osnov i bezbedan backend.', tr:'⚠️ Bu çok hassas verilerdir (kimlik no, doğum tarihi). Bu prototip onları tarayıcıda şifrelemeden saklıyor — gerçek bir lansmandan önce şifreleme, hukuki dayanağın gözden geçirilmesi ve güvenli bir backend şart.', en:'⚠️ This is highly sensitive data (ID number, date of birth). This prototype stores it unencrypted in the browser — a real launch requires encryption, a reviewed legal basis, and a secure backend.', de:'⚠️ Dies sind hochsensible Daten (Ausweisnummer, Geburtsdatum). Dieser Prototyp speichert sie unverschlüsselt im Browser — für einen echten Start sind Verschlüsselung, eine geprüfte Rechtsgrundlage und ein sicheres Backend erforderlich.', fr:'⚠️ Il s\'agit de données très sensibles (numéro d\'identité, date de naissance). Ce prototype les stocke sans chiffrement dans le navigateur — un vrai lancement nécessite un chiffrement, une base légale vérifiée et un backend sécurisé.', it:'⚠️ Questi sono dati molto sensibili (numero documento, data di nascita). Questo prototipo li salva senza crittografia nel browser — un lancio reale richiede crittografia, una base giuridica verificata e un backend sicuro.', bs:'⚠️ Ovo su veoma osjetljivi podaci (ID, datum rođenja). Ovaj prototip ih čuva bez enkripcije u pregledaču — prije pravog lansiranja potrebna je enkripcija, pravni osnov i siguran backend.', el:'⚠️ Πρόκειται για πολύ ευαίσθητα δεδομένα (αριθμός ταυτότητας, ημερομηνία γέννησης). Αυτό το πρωτότυπο τα αποθηκεύει χωρίς κρυπτογράφηση στο πρόγραμμα περιήγησης — μια πραγματική κυκλοφορία απαιτεί κρυπτογράφηση, ελεγμένη νομική βάση και ασφαλές backend.', ru:'⚠️ Это очень чувствительные данные (номер удостоверения, дата рождения). Этот прототип хранит их без шифрования в браузере — для реального запуска необходимы шифрование, проверенное правовое основание и защищённый backend.'},

  nav_my_messages: {sq:'Mesazhet e Mia', sr:'Moje Poruke', tr:'Mesajlarım', en:'My Messages', de:'Meine Nachrichten', fr:'Mes messages', it:'I miei messaggi', bs:'Moje Poruke', el:'Τα Μηνύματά μου', ru:'Мои сообщения'},
  msg_section_title: {sq:'Dërgo Mesazh Shitësit', sr:'Pošalji Poruku Prodavcu', tr:'Satıcıya Mesaj Gönder', en:'Send a Message to the Seller', de:'Nachricht an den Verkäufer senden', fr:'Envoyer un message au vendeur', it:'Invia un messaggio al venditore', bs:'Pošalji Poruku Prodavcu', el:'Στείλτε Μήνυμα στον Πωλητή', ru:'Отправить сообщение продавцу'},
  msg_login_prompt: {sq:'Duhet të hyni në llogari për të dërguar mesazh.', sr:'Morate se prijaviti da biste poslali poruku.', tr:'Mesaj göndermek için giriş yapmalısınız.', en:'You must log in to send a message.', de:'Sie müssen sich anmelden, um eine Nachricht zu senden.', fr:'Vous devez vous connecter pour envoyer un message.', it:'Devi accedere per inviare un messaggio.', bs:'Morate se prijaviti da biste poslali poruku.', el:'Πρέπει να συνδεθείτε για να στείλετε μήνυμα.', ru:'Чтобы отправить сообщение, войдите в аккаунт.'},
  msg_placeholder: {sq:'Shkruani mesazhin tuaj...', sr:'Unesite vašu poruku...', tr:'Mesajınızı yazın...', en:'Write your message...', de:'Schreiben Sie Ihre Nachricht...', fr:'Écrivez votre message...', it:'Scrivi il tuo messaggio...', bs:'Unesite vašu poruku...', el:'Γράψτε το μήνυμά σας...', ru:'Напишите сообщение...'},
  msg_send_button: {sq:'Dërgo', sr:'Pošalji', tr:'Gönder', en:'Send', de:'Senden', fr:'Envoyer', it:'Invia', bs:'Pošalji', el:'Αποστολή', ru:'Отправить'},
  msg_empty_thread: {sq:'Ende asnjë mesazh. Dërgoni të parin!', sr:'Još uvek nema poruka. Pošaljite prvu!', tr:'Henüz mesaj yok. İlk mesajı siz gönderin!', en:'No messages yet. Send the first one!', de:'Noch keine Nachrichten. Senden Sie die erste!', fr:'Aucun message pour l\'instant. Envoyez le premier !', it:'Nessun messaggio ancora. Invia il primo!', bs:'Još uvijek nema poruka. Pošaljite prvu!', el:'Δεν υπάρχουν ακόμη μηνύματα. Στείλτε το πρώτο!', ru:'Пока нет сообщений. Отправьте первое!'},
  toast_msg_sent: {sq:'Mesazhi u dërgua.', sr:'Poruka je poslata.', tr:'Mesajınız gönderildi.', en:'Your message was sent.', de:'Ihre Nachricht wurde gesendet.', fr:'Votre message a été envoyé.', it:'Il tuo messaggio è stato inviato.', bs:'Poruka je poslata.', el:'Το μήνυμά σας στάλθηκε.', ru:'Ваше сообщение отправлено.'},
  toast_msg_empty: {sq:'Ju lutemi shkruani një mesazh.', sr:'Molimo unesite poruku.', tr:'Lütfen bir mesaj yazın.', en:'Please write a message.', de:'Bitte schreiben Sie eine Nachricht.', fr:'Veuillez écrire un message.', it:'Scrivi un messaggio.', bs:'Molimo unesite poruku.', el:'Παρακαλώ γράψτε ένα μήνυμα.', ru:'Пожалуйста, напишите сообщение.'},
  my_messages_empty: {sq:'Ende nuk keni mesazhe.', sr:'Još uvek nemate poruka.', tr:'Henüz mesajınız yok.', en:'You don\'t have any messages yet.', de:'Sie haben noch keine Nachrichten.', fr:'Vous n\'avez pas encore de messages.', it:'Non hai ancora messaggi.', bs:'Još uvijek nemate poruka.', el:'Δεν έχετε ακόμη μηνύματα.', ru:'У вас пока нет сообщений.'},
  msg_regarding_prefix: {sq:'Shpallja:', sr:'Oglas:', tr:'İlan:', en:'Listing:', de:'Anzeige:', fr:'Annonce :', it:'Annuncio:', bs:'Oglas:', el:'Αγγελία:', ru:'Объявление:'},
  admin_tab_members: {sq:'Anëtarët', sr:'Članovi', tr:'Üyeler', en:'Members', de:'Mitglieder', fr:'Membres', it:'Membri', bs:'Članovi', el:'Μέλη', ru:'Участники'},
  admin_tab_messages: {sq:'Mesazhet', sr:'Poruke', tr:'Mesajlar', en:'Messages', de:'Nachrichten', fr:'Messages', it:'Messaggi', bs:'Poruke', el:'Μηνύματα', ru:'Сообщения'},
  admin_col_msg_from: {sq:'Nga', sr:'Od', tr:'Gönderen', en:'From', de:'Von', fr:'De', it:'Da', bs:'Od', el:'Από', ru:'От'},
  admin_col_msg_listing: {sq:'Shpallja', sr:'Oglas', tr:'İlan', en:'Listing', de:'Anzeige', fr:'Annonce', it:'Annuncio', bs:'Oglas', el:'Αγγελία', ru:'Объявление'},
  admin_col_msg_text: {sq:'Mesazhi', sr:'Poruka', tr:'Mesaj', en:'Message', de:'Nachricht', fr:'Message', it:'Messaggio', bs:'Poruka', el:'Μήνυμα', ru:'Сообщение'},
  admin_col_msg_date: {sq:'Data', sr:'Datum', tr:'Tarih', en:'Date', de:'Datum', fr:'Date', it:'Data', bs:'Datum', el:'Ημερομηνία', ru:'Дата'},
  admin_no_messages: {sq:'Ende asnjë mesazh në platformë.', sr:'Još uvek nema poruka na platformi.', tr:'Platformda henüz mesaj yok.', en:'No messages on the platform yet.', de:'Noch keine Nachrichten auf der Plattform.', fr:'Aucun message sur la plateforme pour l\'instant.', it:'Nessun messaggio sulla piattaforma ancora.', bs:'Još uvijek nema poruka na platformi.', el:'Δεν υπάρχουν ακόμη μηνύματα στην πλατφόρμα.', ru:'На платформе пока нет сообщений.'},

  admin_login_title: {sq:'Hyrje e Administratorit', sr:'Administratorska Prijava', tr:'Yönetici Girişi', en:'Admin Login', de:'Admin-Anmeldung', fr:'Connexion admin', it:'Accesso admin', bs:'Administratorska Prijava', el:'Σύνδεση Διαχειριστή', ru:'Вход администратора'},
  admin_login_note: {sq:'Kjo faqe përmban të dhëna të ndjeshme të anëtarëve dhe mesazhet e tyre.', sr:'Ova stranica sadrži osetljive podatke članova i njihove poruke.', tr:'Bu sayfa üyelerin hassas verilerini ve mesajlarını içerir.', en:'This page contains sensitive member data and their messages.', de:'Diese Seite enthält sensible Mitgliederdaten und deren Nachrichten.', fr:'Cette page contient des données sensibles des membres et leurs messages.', it:'Questa pagina contiene dati sensibili dei membri e i loro messaggi.', bs:'Ova stranica sadrži osjetljive podatke članova i njihove poruke.', el:'Αυτή η σελίδα περιέχει ευαίσθητα δεδομένα μελών και τα μηνύματά τους.', ru:'Эта страница содержит конфиденциальные данные участников и их сообщения.'},
  label_admin_username: {sq:'Përdoruesi', sr:'Korisničko ime', tr:'Kullanıcı Adı', en:'Username', de:'Benutzername', fr:'Nom d\'utilisateur', it:'Nome utente', bs:'Korisničko ime', el:'Όνομα χρήστη', ru:'Имя пользователя'},
  btn_admin_login: {sq:'Hyr', sr:'Prijavi se', tr:'Giriş Yap', en:'Log In', de:'Anmelden', fr:'Se connecter', it:'Accedi', bs:'Prijavi se', el:'Σύνδεση', ru:'Войти'},
  toast_admin_wrong_credentials: {sq:'Përdoruesi ose fjalëkalimi i gabuar.', sr:'Pogrešno korisničko ime ili lozinka.', tr:'Kullanıcı adı veya şifre hatalı.', en:'Incorrect username or password.', de:'Falscher Benutzername oder Passwort.', fr:'Nom d\'utilisateur ou mot de passe incorrect.', it:'Nome utente o password errati.', bs:'Pogrešno korisničko ime ili lozinka.', el:'Λανθασμένο όνομα χρήστη ή κωδικός.', ru:'Неверное имя пользователя или пароль.'},
  toast_wrong_password: {sq:'Fjalëkalim i gabuar.', sr:'Pogrešna lozinka.', tr:'Şifre hatalı.', en:'Incorrect password.', de:'Falsches Passwort.', fr:'Mot de passe incorrect.', it:'Password errata.', bs:'Pogrešna lozinka.', el:'Λανθασμένος κωδικός.', ru:'Неверный пароль.'},
  toast_geo_unsupported: {sq:'Shfletuesi juaj nuk e mbështet vendndodhjen.', sr:'Vaš pregledač ne podržava lokaciju.', tr:'Tarayıcınız konum özelliğini desteklemiyor.', en:'Your browser does not support location.', de:'Ihr Browser unterstützt keine Standortermittlung.', fr:'Votre navigateur ne prend pas en charge la localisation.', it:'Il tuo browser non supporta la posizione.', bs:'Vaš pregledač ne podržava lokaciju.', el:'Το πρόγραμμα περιήγησής σας δεν υποστηρίζει τοποθεσία.', ru:'Ваш браузер не поддерживает определение местоположения.'},
  toast_invalid_email: {sq:'Ju lutemi shkruani një email të vlefshëm.', sr:'Unesite validnu email adresu.', tr:'Lütfen geçerli bir e-posta adresi girin.', en:'Please enter a valid email address.', de:'Bitte geben Sie eine gültige E-Mail-Adresse ein.', fr:'Veuillez saisir une adresse e-mail valide.', it:'Inserisci un indirizzo email valido.', bs:'Unesite validnu email adresu.', el:'Παρακαλώ εισαγάγετε μια έγκυρη διεύθυνση email.', ru:'Пожалуйста, введите корректный email.'},

  label_account_type: {sq:'Lloji i Llogarisë', sr:'Tip Naloga', tr:'Hesap Türü', en:'Account Type', de:'Kontotyp', fr:'Type de compte', it:'Tipo di account', bs:'Tip Naloga', el:'Τύπος Λογαριασμού', ru:'Тип аккаунта'},
  option_individual: {sq:'Individual', sr:'Fizičko lice', tr:'Bireysel', en:'Individual', de:'Privatperson', fr:'Particulier', it:'Privato', bs:'Fizičko lice', el:'Ιδιώτης', ru:'Физическое лицо'},
  option_business: {sq:'Biznes / Agjenci', sr:'Firma / Agencija', tr:'Kurumsal / Galeri', en:'Business / Dealer', de:'Firma / Händler', fr:'Entreprise / Agence', it:'Azienda / Agenzia', bs:'Firma / Agencija', el:'Επιχείρηση / Πρακτορείο', ru:'Компания / Агентство'},
  label_company_name: {sq:'Emri i Kompanisë', sr:'Naziv Firme', tr:'Firma Adı', en:'Company Name', de:'Firmenname', fr:'Nom de l\'entreprise', it:'Nome azienda', bs:'Naziv Firme', el:'Επωνυμία Εταιρείας', ru:'Название компании'},
  toast_company_name_required: {sq:'Ju lutemi shkruani emrin e kompanisë.', sr:'Molimo unesite naziv firme.', tr:'Lütfen firma adını girin.', en:'Please enter the company name.', de:'Bitte geben Sie den Firmennamen ein.', fr:'Veuillez saisir le nom de l\'entreprise.', it:'Inserisci il nome dell\'azienda.', bs:'Molimo unesite naziv firme.', el:'Παρακαλώ εισαγάγετε την επωνυμία της εταιρείας.', ru:'Пожалуйста, укажите название компании.'},
  badge_business_account: {sq:'Llogari Biznesi', sr:'Poslovni Nalog', tr:'Kurumsal Üye', en:'Business Account', de:'Geschäftskonto', fr:'Compte professionnel', it:'Account aziendale', bs:'Poslovni Nalog', el:'Επαγγελματικός Λογαριασμός', ru:'Бизнес-аккаунт'},
  admin_col_account_type: {sq:'Lloji', sr:'Tip', tr:'Hesap Türü', en:'Type', de:'Typ', fr:'Type', it:'Tipo', bs:'Tip', el:'Τύπος', ru:'Тип'},

  switch_to_forgot: {sq:'Keni harruar fjalëkalimin?', sr:'Zaboravili ste lozinku?', tr:'Şifremi Unuttum', en:'Forgot Password?', de:'Passwort vergessen?', fr:'Mot de passe oublié ?', it:'Password dimenticata?', bs:'Zaboravili ste lozinku?', el:'Ξεχάσατε τον κωδικό;', ru:'Забыли пароль?'},
  forgot_note: {sq:'Do t\'ju dërgojmë një lidhje me email për të rivendosur fjalëkalimin.', sr:'Poslaćemo vam email sa linkom za resetovanje lozinke.', tr:'Şifrenizi sıfırlamanız için e-posta ile bir bağlantı göndereceğiz.', en:'We\'ll send you an email with a link to reset your password.', de:'Wir senden Ihnen eine E-Mail mit einem Link zum Zurücksetzen Ihres Passworts.', fr:'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe.', it:'Ti invieremo un\'email con un link per reimpostare la password.', bs:'Poslaćemo vam email sa linkom za resetovanje lozinke.', el:'Θα σας στείλουμε email με σύνδεσμο επαναφοράς κωδικού.', ru:'Мы отправим вам письмо со ссылкой для сброса пароля.'},
  label_new_password: {sq:'Fjalëkalimi i Ri', sr:'Nova Lozinka', tr:'Yeni Şifre', en:'New Password', de:'Neues Passwort', fr:'Nouveau mot de passe', it:'Nuova password', bs:'Nova Lozinka', el:'Νέος Κωδικός', ru:'Новый пароль'},
  label_new_password_confirm: {sq:'Përsërit Fjalëkalimin e Ri', sr:'Ponovi Novu Lozinku', tr:'Yeni Şifre Tekrar', en:'Confirm New Password', de:'Neues Passwort bestätigen', fr:'Confirmer le nouveau mot de passe', it:'Conferma nuova password', bs:'Ponovi Novu Lozinku', el:'Επιβεβαίωση Νέου Κωδικού', ru:'Повторите новый пароль'},
  btn_reset_password: {sq:'Rivendos Fjalëkalimin', sr:'Resetuj Lozinku', tr:'Şifreyi Sıfırla', en:'Reset Password', de:'Passwort zurücksetzen', fr:'Réinitialiser le mot de passe', it:'Reimposta password', bs:'Resetuj Lozinku', el:'Επαναφορά Κωδικού', ru:'Сбросить пароль'},
  back_to_login: {sq:'Kthehu te Hyrja', sr:'Nazad na Prijavu', tr:'Girişe Dön', en:'Back to Login', de:'Zurück zur Anmeldung', fr:'Retour à la connexion', it:'Torna al login', bs:'Nazad na Prijavu', el:'Πίσω στη Σύνδεση', ru:'Назад ко входу'},
  toast_forgot_no_match: {sq:'Email dhe datëlindja nuk përputhen me asnjë llogari.', sr:'Email i datum rođenja se ne poklapaju ni sa jednim nalogom.', tr:'E-posta ve doğum tarihi hiçbir hesapla eşleşmiyor.', en:'Email and date of birth don\'t match any account.', de:'E-Mail und Geburtsdatum stimmen mit keinem Konto überein.', fr:'L\'e-mail et la date de naissance ne correspondent à aucun compte.', it:'Email e data di nascita non corrispondono a nessun account.', bs:'Email i datum rođenja se ne poklapaju ni sa jednim nalogom.', el:'Το email και η ημερομηνία γέννησης δεν ταιριάζουν με κανέναν λογαριασμό.', ru:'Email и дата рождения не совпадают ни с одним аккаунтом.'},
  toast_password_reset_success: {sq:'Fjalëkalimi u ndryshua me sukses. Tani mund të hyni.', sr:'Lozinka je uspešno promenjena. Sada se možete prijaviti.', tr:'Şifreniz başarıyla değiştirildi. Şimdi giriş yapabilirsiniz.', en:'Your password was reset successfully. You can now log in.', de:'Ihr Passwort wurde erfolgreich zurückgesetzt. Sie können sich jetzt anmelden.', fr:'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter.', it:'La tua password è stata reimpostata con successo. Ora puoi accedere.', bs:'Lozinka je uspješno promijenjena. Sada se možete prijaviti.', el:'Ο κωδικός σας επαναφέρθηκε με επιτυχία. Μπορείτε τώρα να συνδεθείτε.', ru:'Ваш пароль успешно сброшен. Теперь вы можете войти.'},

  nav_my_listings: {sq:'Shpalljet e Mia', sr:'Moji Oglasi', tr:'İlanlarım', en:'My Listings', de:'Meine Anzeigen', fr:'Mes annonces', it:'I miei annunci', bs:'Moji Oglasi', el:'Οι Αγγελίες μου', ru:'Мои объявления'},
  nav_my_favorites: {sq:'Të Preferuarat', sr:'Omiljeno', tr:'Favorilerim', en:'My Favorites', de:'Meine Favoriten', fr:'Mes favoris', it:'I miei preferiti', bs:'Omiljeno', el:'Αγαπημένα', ru:'Избранное'},
  btn_favorite: {sq:'Ruaj', sr:'Sačuvaj', tr:'Favorile', en:'Favorite', de:'Merken', fr:'Favoris', it:'Preferiti', bs:'Sačuvaj', el:'Αγαπημένο', ru:'В избранное'},
  edit_ad_title: {sq:'Ndrysho Shpalljen', sr:'Izmeni Oglas', tr:'İlanı Düzenle', en:'Edit Listing', de:'Anzeige bearbeiten', fr:'Modifier l\'annonce', it:'Modifica annuncio', bs:'Izmijeni Oglas', el:'Επεξεργασία Αγγελίας', ru:'Редактировать объявление'},
  my_listings_empty: {sq:'Ende nuk keni shpallje.', sr:'Još uvek nemate oglase.', tr:'Henüz ilanınız yok.', en:'You don\'t have any listings yet.', de:'Sie haben noch keine Anzeigen.', fr:'Vous n\'avez pas encore d\'annonces.', it:'Non hai ancora annunci.', bs:'Još uvijek nemate oglase.', el:'Δεν έχετε ακόμη αγγελίες.', ru:'У вас пока нет объявлений.'},
  btn_edit: {sq:'Ndrysho', sr:'Izmeni', tr:'Düzenle', en:'Edit', de:'Bearbeiten', fr:'Modifier', it:'Modifica', bs:'Izmijeni', el:'Επεξεργασία', ru:'Изменить'},
  btn_save: {sq:'Ruaj Ndryshimet', sr:'Sačuvaj Izmene', tr:'Değişiklikleri Kaydet', en:'Save Changes', de:'Änderungen speichern', fr:'Enregistrer les modifications', it:'Salva modifiche', bs:'Sačuvaj Izmjene', el:'Αποθήκευση Αλλαγών', ru:'Сохранить изменения'},
  btn_delete: {sq:'Fshi', sr:'Obriši', tr:'Sil', en:'Delete', de:'Löschen', fr:'Supprimer', it:'Elimina', bs:'Obriši', el:'Διαγραφή', ru:'Удалить'},
  confirm_delete_listing: {sq:'A jeni i sigurt që doni ta fshini këtë shpallje?', sr:'Da li ste sigurni da želite da obrišete ovaj oglas?', tr:'Bu ilanı silmek istediğinizden emin misiniz?', en:'Are you sure you want to delete this listing?', de:'Möchten Sie diese Anzeige wirklich löschen?', fr:'Voulez-vous vraiment supprimer cette annonce ?', it:'Sei sicuro di voler eliminare questo annuncio?', bs:'Da li ste sigurni da želite da obrišete ovaj oglas?', el:'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτή την αγγελία;', ru:'Вы уверены, что хотите удалить это объявление?'},
  toast_ad_updated: {sq:'Shpallja u përditësua me sukses.', sr:'Oglas je uspešno ažuriran.', tr:'İlan başarıyla güncellendi.', en:'Listing updated successfully.', de:'Anzeige erfolgreich aktualisiert.', fr:'Annonce mise à jour avec succès.', it:'Annuncio aggiornato con successo.', bs:'Oglas je uspješno ažuriran.', el:'Η αγγελία ενημερώθηκε με επιτυχία.', ru:'Объявление успешно обновлено.'},
  toast_ad_deleted: {sq:'Shpallja u fshi.', sr:'Oglas je obrisan.', tr:'İlan silindi.', en:'Listing deleted.', de:'Anzeige gelöscht.', fr:'Annonce supprimée.', it:'Annuncio eliminato.', bs:'Oglas je obrisan.', el:'Η αγγελία διαγράφηκε.', ru:'Объявление удалено.'},
  my_favorites_empty: {sq:'Ende nuk keni shpallje të preferuara.', sr:'Još uvek nemate omiljene oglase.', tr:'Henüz favori ilanınız yok.', en:'You don\'t have any favorite listings yet.', de:'Sie haben noch keine favorisierten Anzeigen.', fr:'Vous n\'avez pas encore d\'annonces favorites.', it:'Non hai ancora annunci preferiti.', bs:'Još uvijek nemate omiljene oglase.', el:'Δεν έχετε ακόμη αγαπημένες αγγελίες.', ru:'У вас пока нет избранных объявлений.'},
  btn_remove: {sq:'Hiq', sr:'Ukloni', tr:'Kaldır', en:'Remove', de:'Entfernen', fr:'Retirer', it:'Rimuovi', bs:'Ukloni', el:'Αφαίρεση', ru:'Убрать'},

  report_listing_link: {sq:'Raporto këtë shpallje', sr:'Prijavi ovaj oglas', tr:'Bu ilanı şikayet et', en:'Report this listing', de:'Diese Anzeige melden', fr:'Signaler cette annonce', it:'Segnala questo annuncio', bs:'Prijavi ovaj oglas', el:'Αναφορά αυτής της αγγελίας', ru:'Пожаловаться на объявление'},
  report_modal_title: {sq:'Raporto Shpalljen', sr:'Prijavi Oglas', tr:'İlanı Şikayet Et', en:'Report Listing', de:'Anzeige melden', fr:'Signaler l\'annonce', it:'Segnala annuncio', bs:'Prijavi Oglas', el:'Αναφορά Αγγελίας', ru:'Пожаловаться на объявление'},
  label_report_reason: {sq:'Arsyeja', sr:'Razlog', tr:'Sebep', en:'Reason', de:'Grund', fr:'Raison', it:'Motivo', bs:'Razlog', el:'Λόγος', ru:'Причина'},
  reason_fraud: {sq:'Mashtrim', sr:'Prevara', tr:'Dolandırıcılık', en:'Fraud', de:'Betrug', fr:'Fraude', it:'Frode', bs:'Prevara', el:'Απάτη', ru:'Мошенничество'},
  reason_misleading: {sq:'Informacion mashtrues', sr:'Zavaravajuće informacije', tr:'Yanıltıcı bilgi', en:'Misleading information', de:'Irreführende Informationen', fr:'Informations trompeuses', it:'Informazioni fuorvianti', bs:'Zavaravajuće informacije', el:'Παραπλανητικές πληροφορίες', ru:'Вводящая в заблуждение информация'},
  reason_inappropriate: {sq:'Përmbajtje e papërshtatshme', sr:'Neprikladan sadržaj', tr:'Uygunsuz içerik', en:'Inappropriate content', de:'Unangemessener Inhalt', fr:'Contenu inapproprié', it:'Contenuto inappropriato', bs:'Neprikladan sadržaj', el:'Ακατάλληλο περιεχόμενο', ru:'Неприемлемый контент'},
  reason_other: {sq:'Tjetër', sr:'Ostalo', tr:'Diğer', en:'Other', de:'Sonstiges', fr:'Autre', it:'Altro', bs:'Ostalo', el:'Άλλο', ru:'Другое'},
  label_report_details: {sq:'Detaje (opsionale)', sr:'Detalji (opciono)', tr:'Detaylar (opsiyonel)', en:'Details (optional)', de:'Details (optional)', fr:'Détails (facultatif)', it:'Dettagli (facoltativo)', bs:'Detalji (opciono)', el:'Λεπτομέρειες (προαιρετικό)', ru:'Подробности (необязательно)'},
  btn_submit_report: {sq:'Dërgo Raportin', sr:'Pošalji Prijavu', tr:'Şikayeti Gönder', en:'Submit Report', de:'Meldung senden', fr:'Envoyer le signalement', it:'Invia segnalazione', bs:'Pošalji Prijavu', el:'Υποβολή Αναφοράς', ru:'Отправить жалобу'},
  toast_report_submitted: {sq:'Faleminderit, raporti u dërgua.', sr:'Hvala, prijava je poslata.', tr:'Teşekkürler, şikayetiniz gönderildi.', en:'Thank you, your report has been submitted.', de:'Danke, Ihre Meldung wurde gesendet.', fr:'Merci, votre signalement a été envoyé.', it:'Grazie, la tua segnalazione è stata inviata.', bs:'Hvala, prijava je poslata.', el:'Ευχαριστούμε, η αναφορά σας υποβλήθηκε.', ru:'Спасибо, ваша жалоба отправлена.'},
  admin_tab_reports: {sq:'Raportimet', sr:'Prijave', tr:'Şikayetler', en:'Reports', de:'Meldungen', fr:'Signalements', it:'Segnalazioni', bs:'Prijave', el:'Αναφορές', ru:'Жалобы'},
  admin_no_reports: {sq:'Ende asnjë raportim.', sr:'Još uvek nema prijava.', tr:'Henüz şikayet yok.', en:'No reports yet.', de:'Noch keine Meldungen.', fr:'Aucun signalement pour l\'instant.', it:'Nessuna segnalazione ancora.', bs:'Još uvijek nema prijava.', el:'Δεν υπάρχουν ακόμη αναφορές.', ru:'Пока нет жалоб.'},
  admin_col_report_from: {sq:'Raportuar nga', sr:'Prijavio', tr:'Bildiren', en:'Reported by', de:'Gemeldet von', fr:'Signalé par', it:'Segnalato da', bs:'Prijavio', el:'Αναφέρθηκε από', ru:'Кем подано'},
  admin_col_report_reason: {sq:'Arsyeja', sr:'Razlog', tr:'Sebep', en:'Reason', de:'Grund', fr:'Raison', it:'Motivo', bs:'Razlog', el:'Λόγος', ru:'Причина'},
  admin_col_report_details: {sq:'Detajet', sr:'Detalji', tr:'Detay', en:'Details', de:'Details', fr:'Détails', it:'Dettagli', bs:'Detalji', el:'Λεπτομέρειες', ru:'Подробности'},
  btn_remove_listing: {sq:'Hiq Shpalljen', sr:'Ukloni Oglas', tr:'İlanı Kaldır', en:'Remove Listing', de:'Anzeige entfernen', fr:'Retirer l\'annonce', it:'Rimuovi annuncio', bs:'Ukloni Oglas', el:'Αφαίρεση Αγγελίας', ru:'Удалить объявление'},
  already_removed: {sq:'Tashmë e hequr', sr:'Već uklonjeno', tr:'Zaten kaldırıldı', en:'Already removed', de:'Bereits entfernt', fr:'Déjà retiré', it:'Già rimosso', bs:'Već uklonjeno', el:'Ήδη αφαιρέθηκε', ru:'Уже удалено'},

  label_photos: {sq:'Fotografitë', sr:'Fotografije', tr:'Fotoğraflar', en:'Photos', de:'Fotos', fr:'Photos', it:'Foto', bs:'Fotografije', el:'Φωτογραφίες', ru:'Фотографии'},
  photo_upload_hint: {sq:'Deri në 5 foto. Do të ngjeshen automatikisht.', sr:'Do 5 fotografija. Biće automatski kompresovane.', tr:'En fazla 5 fotoğraf. Otomatik olarak sıkıştırılır.', en:'Up to 5 photos. They will be compressed automatically.', de:'Bis zu 5 Fotos. Sie werden automatisch komprimiert.', fr:'Jusqu\'à 5 photos. Elles seront automatiquement compressées.', it:'Fino a 5 foto. Verranno compresse automaticamente.', bs:'Do 5 fotografija. Biće automatski kompresovane.', el:'Έως 5 φωτογραφίες. Θα συμπιεστούν αυτόματα.', ru:'До 5 фото. Они будут автоматически сжаты.'},
  toast_photo_limit: {sq:'Maksimumi 5 foto për shpallje.', sr:'Maksimalno 5 fotografija po oglasu.', tr:'İlan başına en fazla 5 fotoğraf.', en:'Maximum 5 photos per listing.', de:'Maximal 5 Fotos pro Anzeige.', fr:'Maximum 5 photos par annonce.', it:'Massimo 5 foto per annuncio.', bs:'Maksimalno 5 fotografija po oglasu.', el:'Έως 5 φωτογραφίες ανά αγγελία.', ru:'Максимум 5 фото на объявление.'},
  toast_storage_full: {sq:'Hapësira ruajtëse e shfletuesit është plot. Provoni foto më të vogla ose më pak foto.', sr:'Prostor za skladištenje pregledača je pun. Probajte manje ili manje fotografija.', tr:'Tarayıcı depolama alanı dolu. Daha az veya daha küçük fotoğraf deneyin.', en:'Browser storage is full. Try fewer or smaller photos.', de:'Der Browser-Speicher ist voll. Versuchen Sie weniger oder kleinere Fotos.', fr:'Le stockage du navigateur est plein. Essayez moins de photos ou des photos plus petites.', it:'Lo spazio di archiviazione del browser è pieno. Prova con meno foto o foto più piccole.', bs:'Prostor za skladištenje pregledača je pun. Probajte manje ili manje fotografija.', el:'Ο αποθηκευτικός χώρος του προγράμματος περιήγησης είναι πλήρης. Δοκιμάστε λιγότερες ή μικρότερες φωτογραφίες.', ru:'Хранилище браузера заполнено. Попробуйте меньше фото или файлы поменьше.'},

  logout_button: {sq:'Dilni', sr:'Odjava', tr:'Çıkış Yap', en:'Log Out', de:'Abmelden', fr:'Déconnexion', it:'Esci', bs:'Odjava', el:'Αποσύνδεση', ru:'Выйти'},
  toast_check_email_confirm: {sq:'Ju regjistruat! Kontrolloni email-in tuaj për të konfirmuar llogarinë.', sr:'Registracija uspešna! Proverite email da potvrdite nalog.', tr:'Kayıt başarılı! Hesabınızı onaylamak için e-postanızı kontrol edin.', en:'Registered! Check your email to confirm your account.', de:'Registrierung erfolgreich! Bestätigen Sie Ihr Konto per E-Mail.', fr:'Inscription réussie ! Vérifiez votre e-mail pour confirmer votre compte.', it:'Registrazione riuscita! Controlla la tua email per confermare l\'account.', bs:'Registracija uspješna! Provjerite email da potvrdite nalog.', el:'Επιτυχής εγγραφή! Ελέγξτε το email σας για επιβεβαίωση.', ru:'Регистрация успешна! Проверьте почту для подтверждения аккаунта.'},
  toast_check_email_reset: {sq:'Nëse email-i ekziston, ju kemi dërguar një lidhje për rivendosjen e fjalëkalimit.', sr:'Ako email postoji, poslali smo vam link za resetovanje lozinke.', tr:'E-posta kayıtlıysa, şifre sıfırlama bağlantısı gönderildi.', en:'If that email exists, we\'ve sent a password reset link.', de:'Falls diese E-Mail existiert, haben wir einen Link zum Zurücksetzen gesendet.', fr:'Si cet e-mail existe, nous avons envoyé un lien de réinitialisation.', it:'Se l\'email esiste, abbiamo inviato un link per reimpostare la password.', bs:'Ako email postoji, poslali smo vam link za resetovanje lozinke.', el:'Αν υπάρχει αυτό το email, στείλαμε σύνδεσμο επαναφοράς κωδικού.', ru:'Если такая почта существует, мы отправили ссылку для сброса пароля.'},
  error_generic: {sq:'Diçka shkoi keq. Provoni përsëri.', sr:'Nešto je pošlo po zlu. Pokušajte ponovo.', tr:'Bir şeyler ters gitti. Tekrar deneyin.', en:'Something went wrong. Please try again.', de:'Etwas ist schiefgelaufen. Bitte erneut versuchen.', fr:'Une erreur est survenue. Veuillez réessayer.', it:'Qualcosa è andato storto. Riprova.', bs:'Nešto je pošlo po zlu. Pokušajte ponovo.', el:'Κάτι πήγε στραβά. Δοκιμάστε ξανά.', ru:'Что-то пошло не так. Попробуйте снова.'},

  nav_packages: {sq:'Paketat', sr:'Paketi', tr:'Paketler', en:'Packages', de:'Pakete', fr:'Forfaits', it:'Pacchetti', bs:'Paketi', el:'Πακέτα', ru:'Пакеты'},
  packages_title: {sq:'Paketat & Kreditet', sr:'Paketi i Krediti', tr:'Paketler ve Krediler', en:'Packages & Credits', de:'Pakete & Guthaben', fr:'Forfaits et crédits', it:'Pacchetti e crediti', bs:'Paketi i Krediti', el:'Πακέτα & Πιστώσεις', ru:'Пакеты и кредиты'},
  packages_subtitle: {sq:'Përmirësoni planin ose blini kredite për të publikuar dhe promovuar më shumë shpallje.', sr:'Nadogradite plan ili kupite kredite da objavite i promovišete više oglasa.', tr:'Daha fazla ilan yayınlamak ve öne çıkarmak için planınızı yükseltin veya kredi satın alın.', en:'Upgrade your plan or buy credits to publish and promote more listings.', de:'Upgraden Sie Ihren Plan oder kaufen Sie Guthaben, um mehr Anzeigen zu veröffentlichen und zu bewerben.', fr:'Améliorez votre forfait ou achetez des crédits pour publier et promouvoir plus d\'annonces.', it:'Aggiorna il tuo piano o acquista crediti per pubblicare e promuovere più annunci.', bs:'Nadogradite plan ili kupite kredite da objavite i promovišete više oglasa.', el:'Αναβαθμίστε το πλάνο σας ή αγοράστε πιστώσεις για να δημοσιεύσετε περισσότερες αγγελίες.', ru:'Улучшите план или купите кредиты, чтобы публиковать и продвигать больше объявлений.'},
  packages_subscription_title: {sq:'Paketat e Abonimit', sr:'Pretplatnički Paketi', tr:'Abonelik Paketleri', en:'Subscription Packages', de:'Abo-Pakete', fr:'Forfaits d\'abonnement', it:'Pacchetti in abbonamento', bs:'Pretplatnički Paketi', el:'Πακέτα Συνδρομής', ru:'Пакеты подписки'},
  plan_standard_name: {sq:'Standard', sr:'Standard', tr:'Standart', en:'Standard', de:'Standard', fr:'Standard', it:'Standard', bs:'Standard', el:'Βασικό', ru:'Стандарт'},
  plan_premium_name: {sq:'Premium', sr:'Premium', tr:'Premium', en:'Premium', de:'Premium', fr:'Premium', it:'Premium', bs:'Premium', el:'Premium', ru:'Премиум'},
  plan_enterprise_name: {sq:'Enterprise', sr:'Enterprise', tr:'Kurumsal', en:'Enterprise', de:'Enterprise', fr:'Entreprise', it:'Enterprise', bs:'Enterprise', el:'Enterprise', ru:'Корпоративный'},
  plan_default_badge: {sq:'Parazgjedhur', sr:'Podrazumevano', tr:'Varsayılan', en:'Default', de:'Standard', fr:'Par défaut', it:'Predefinito', bs:'Podrazumijevano', el:'Προεπιλογή', ru:'По умолчанию'},
  plan_most_popular: {sq:'MË TË NJOHURA', sr:'NAJPOPULARNIJE', tr:'EN POPÜLER', en:'MOST POPULAR', de:'AM BELIEBTESTEN', fr:'LE PLUS POPULAIRE', it:'PIÙ POPOLARE', bs:'NAJPOPULARNIJE', el:'ΔΗΜΟΦΙΛΕΣΤΕΡΟ', ru:'САМЫЙ ПОПУЛЯРНЫЙ'},
  plan_per_month: {sq:'/ muaj', sr:'/ mesec', tr:'/ ay', en:'/ month', de:'/ Monat', fr:'/ mois', it:'/ mese', bs:'/ mjesec', el:'/ μήνα', ru:'/ месяц'},
  plan_listings_suffix: {sq:'shpallje', sr:'oglasa', tr:'ilan', en:'listings', de:'Anzeigen', fr:'annonces', it:'annunci', bs:'oglasa', el:'αγγελίες', ru:'объявлений'},
  plan_showcase_suffix: {sq:'vende vitrine', sr:'mesta na vitrini', tr:'vitrin alanı', en:'showcase spots', de:'Vitrinenplätze', fr:'emplacements vitrine', it:'posti in vetrina', bs:'mjesta na vitrini', el:'θέσεις βιτρίνας', ru:'мест в витрине'},
  btn_login_to_buy: {sq:'Hyr për të blerë', sr:'Prijavite se za kupovinu', tr:'Satın almak için giriş yapın', en:'Log in to buy', de:'Zum Kauf anmelden', fr:'Connectez-vous pour acheter', it:'Accedi per acquistare', bs:'Prijavite se za kupovinu', el:'Συνδεθείτε για αγορά', ru:'Войдите, чтобы купить'},
  btn_buy: {sq:'Blej', sr:'Kupi', tr:'Satın Al', en:'Buy', de:'Kaufen', fr:'Acheter', it:'Acquista', bs:'Kupi', el:'Αγορά', ru:'Купить'},
  btn_current_plan: {sq:'Plani Aktual', sr:'Trenutni Plan', tr:'Mevcut Plan', en:'Current Plan', de:'Aktueller Plan', fr:'Forfait actuel', it:'Piano attuale', bs:'Trenutni Plan', el:'Τρέχον Πλάνο', ru:'Текущий план'},
  plan_custom_title: {sq:'Paketë e Personalizuar', sr:'Prilagođeni Paket', tr:'Özel Paket', en:'Custom Package', de:'Individuelles Paket', fr:'Forfait personnalisé', it:'Pacchetto personalizzato', bs:'Prilagođeni Paket', el:'Προσαρμοσμένο Πακέτο', ru:'Индивидуальный пакет'},
  plan_custom_subtitle: {sq:'Çmim sipas nevojave tuaja', sr:'Cena prema vašim potrebama', tr:'İhtiyaçlarınıza göre fiyat', en:'Pricing based on your needs', de:'Preis nach Ihren Bedürfnissen', fr:'Tarif selon vos besoins', it:'Prezzo in base alle tue esigenze', bs:'Cijena prema vašim potrebama', el:'Τιμή ανάλογα με τις ανάγκες σας', ru:'Цена по вашим потребностям'},
  plan_custom_unlimited: {sq:'Pa limit shpallje', sr:'Neograničeno oglasa', tr:'Sınırsız ilan', en:'Unlimited listings', de:'Unbegrenzte Anzeigen', fr:'Annonces illimitées', it:'Annunci illimitati', bs:'Neograničeno oglasa', el:'Απεριόριστες αγγελίες', ru:'Неограниченные объявления'},
  plan_custom_priority: {sq:'Mbështetje prioritare', sr:'Prioritetna podrška', tr:'Öncelikli destek', en:'Priority support', de:'Prioritäts-Support', fr:'Support prioritaire', it:'Supporto prioritario', bs:'Prioritetna podrška', el:'Υποστήριξη προτεραιότητας', ru:'Приоритетная поддержка'},
  plan_custom_tailored: {sq:'Zgjidhje sipas nevojave tuaja', sr:'Rešenja prema vašim potrebama', tr:'İhtiyaçlarınıza özel çözümler', en:'Tailored solutions', de:'Maßgeschneiderte Lösungen', fr:'Solutions sur mesure', it:'Soluzioni su misura', bs:'Rješenja prema vašim potrebama', el:'Λύσεις προσαρμοσμένες σε εσάς', ru:'Индивидуальные решения'},
  btn_contact_us: {sq:'Na Kontaktoni', sr:'Kontaktirajte Nas', tr:'Bize Ulaşın', en:'Contact Us', de:'Kontaktieren Sie uns', fr:'Contactez-nous', it:'Contattaci', bs:'Kontaktirajte Nas', el:'Επικοινωνήστε μαζί μας', ru:'Свяжитесь с нами'},
  packages_credits_title: {sq:'Kredite Një-herëshe', sr:'Jednokratni Krediti', tr:'Tek Seferlik Krediler', en:'One-time Credits', de:'Einmalige Guthaben', fr:'Crédits ponctuels', it:'Crediti una tantum', bs:'Jednokratni Krediti', el:'Εφάπαξ Πιστώσεις', ru:'Разовые кредиты'},
  packages_credits_subtitle: {sq:'Zgjidhni sasitë dhe paguani gjithçka në një transaksion.', sr:'Izaberite količine i platite sve u jednoj transakciji.', tr:'Miktarları seçin ve her şeyi tek işlemde ödeyin.', en:'Choose quantities and pay everything in one transaction.', de:'Wählen Sie Mengen und bezahlen Sie alles in einer Transaktion.', fr:'Choisissez les quantités et payez tout en une seule transaction.', it:'Scegli le quantità e paga tutto in un\'unica transazione.', bs:'Izaberite količine i platite sve u jednoj transakciji.', el:'Επιλέξτε ποσότητες και πληρώστε τα πάντα σε μία συναλλαγή.', ru:'Выберите количество и оплатите всё одной транзакцией.'},
  credit_extra_listing_name: {sq:'Shpallje Shtesë', sr:'Dodatni Oglas', tr:'Ekstra İlan', en:'Extra Listing', de:'Zusätzliche Anzeige', fr:'Annonce supplémentaire', it:'Annuncio extra', bs:'Dodatni Oglas', el:'Επιπλέον Αγγελία', ru:'Дополнительное объявление'},
  credit_urgent_tag_name: {sq:'Etiketë Urgjente', sr:'Hitna Oznaka', tr:'Acil Etiketi', en:'Urgent Tag', de:'Dringend-Label', fr:'Étiquette urgente', it:'Etichetta urgente', bs:'Hitna Oznaka', el:'Ετικέτα Επείγον', ru:'Метка "Срочно"'},
  credit_extra_showcase_name: {sq:'Vitrinë Shtesë', sr:'Dodatna Vitrina', tr:'Ekstra Vitrin', en:'Extra Showcase', de:'Zusätzliche Vitrine', fr:'Vitrine supplémentaire', it:'Vetrina extra', bs:'Dodatna Vitrina', el:'Επιπλέον Βιτρίνα', ru:'Дополнительная витрина'},
  credit_highlight_name: {sq:'Theksim', sr:'Isticanje', tr:'Öne Çıkarma', en:'Highlight', de:'Hervorhebung', fr:'Mise en avant', it:'Evidenziazione', bs:'Isticanje', el:'Επισήμανση', ru:'Выделение'},
  packages_your_balance: {sq:'Bilanci juaj', sr:'Vaš saldo', tr:'Bakiyeniz', en:'Your balance', de:'Ihr Guthaben', fr:'Votre solde', it:'Il tuo saldo', bs:'Vaš saldo', el:'Το υπόλοιπό σας', ru:'Ваш баланс'},
  packages_payment_note: {sq:'Ky është një pagesë demo — ende nuk përpunohet asnjë pagesë reale.', sr:'Ovo je demo plaćanje — još uvek se ne obrađuje stvarno plaćanje.', tr:'Bu bir demo ödemedir — henüz gerçek bir ödeme işlenmiyor.', en:'This is a demo checkout — no real payment is processed yet.', de:'Dies ist eine Demo-Zahlung — es wird noch keine echte Zahlung verarbeitet.', fr:'Ceci est un paiement de démonstration — aucun paiement réel n\'est encore traité.', it:'Questo è un pagamento demo — nessun pagamento reale viene ancora elaborato.', bs:'Ovo je demo plaćanje — još uvijek se ne obrađuje stvarno plaćanje.', el:'Αυτή είναι μια δοκιμαστική πληρωμή — δεν επεξεργαζόμαστε ακόμη πραγματική πληρωμή.', ru:'Это демо-оплата — реальный платёж пока не обрабатывается.'},
  toast_purchase_success: {sq:'Blerja u krye me sukses!', sr:'Kupovina uspešna!', tr:'Satın alma başarılı!', en:'Purchase successful!', de:'Kauf erfolgreich!', fr:'Achat réussi !', it:'Acquisto riuscito!', bs:'Kupovina uspješna!', el:'Η αγορά ολοκληρώθηκε!', ru:'Покупка выполнена!'},

  label_urgent_tag: {sq:'Shëno si urgjente', sr:'Označi kao hitno', tr:'Acil olarak işaretle', en:'Mark as urgent', de:'Als dringend markieren', fr:'Marquer comme urgent', it:'Segna come urgente', bs:'Označi kao hitno', el:'Σήμανση ως επείγον', ru:'Отметить как срочное'},
  label_highlight: {sq:'Theksoje këtë shpallje', sr:'Istakni ovaj oglas', tr:'Bu ilanı öne çıkar', en:'Highlight this listing', de:'Diese Anzeige hervorheben', fr:'Mettre en avant cette annonce', it:'Evidenzia questo annuncio', bs:'Istakni ovaj oglas', el:'Επισήμανση αυτής της αγγελίας', ru:'Выделить это объявление'},
  label_showcase: {sq:'Vendose në vitrinë', sr:'Postavi u vitrinu', tr:'Vitrine ekle', en:'Feature in showcase', de:'In Vitrine anzeigen', fr:'Mettre en vitrine', it:'Metti in vetrina', bs:'Postavi u vitrinu', el:'Προβολή στη βιτρίνα', ru:'Добавить в витрину'},
  badge_urgent: {sq:'URGJENTE', sr:'HITNO', tr:'ACİL', en:'URGENT', de:'DRINGEND', fr:'URGENT', it:'URGENTE', bs:'HITNO', el:'ΕΠΕΙΓΟΝ', ru:'СРОЧНО'},
  badge_highlighted: {sq:'E VEÇUAR', sr:'ISTAKNUTO', tr:'ÖNE ÇIKAN', en:'FEATURED', de:'HERVORGEHOBEN', fr:'EN VEDETTE', it:'IN EVIDENZA', bs:'ISTAKNUTO', el:'ΕΠΙΣΗΜΑΣΜΕΝΟ', ru:'РЕКОМЕНДУЕМОЕ'},
  credits_available_suffix: {sq:'në dispozicion', sr:'dostupno', tr:'kullanılabilir', en:'available', de:'verfügbar', fr:'disponible(s)', it:'disponibili', bs:'dostupno', el:'διαθέσιμα', ru:'доступно'},
  toast_no_credits: {sq:'Nuk keni kredite për këtë. Blini në Paketa.', sr:'Nemate kredita za ovo. Kupite u Paketima.', tr:'Bunun için krediniz yok. Paketler\'den satın alın.', en:'You don\'t have credits for this. Buy some in Packages.', de:'Sie haben kein Guthaben dafür. Kaufen Sie welches unter Pakete.', fr:'Vous n\'avez pas de crédits pour cela. Achetez-en dans Forfaits.', it:'Non hai crediti per questo. Acquistane in Pacchetti.', bs:'Nemate kredita za ovo. Kupite u Paketima.', el:'Δεν έχετε πιστώσεις για αυτό. Αγοράστε στα Πακέτα.', ru:'У вас нет кредитов для этого. Купите в разделе Пакеты.'},

  nav_gallery: {sq:'Bizneset', sr:'Preduzeća', tr:'İşletmeler', en:'Businesses', de:'Unternehmen', fr:'Entreprises', it:'Aziende', bs:'Preduzeća', el:'Επιχειρήσεις', ru:'Компании'},
  gallery_title: {sq:'Drejtoria e Bizneseve', sr:'Direktorijum Preduzeća', tr:'İşletme Rehberi', en:'Business Directory', de:'Unternehmensverzeichnis', fr:'Annuaire des entreprises', it:'Elenco aziende', bs:'Direktorij Preduzeća', el:'Κατάλογος Επιχειρήσεων', ru:'Каталог компаний'},
  gallery_vehicles_tab: {sq:'Tregtarë Automjetesh', sr:'Prodavci Vozila', tr:'Araç Bayileri', en:'Car Dealers', de:'Autohändler', fr:'Concessionnaires auto', it:'Concessionari auto', bs:'Prodavci Vozila', el:'Έμποροι Αυτοκινήτων', ru:'Автодилеры'},
  gallery_realestate_tab: {sq:'Kompani Patundshmërie', sr:'Agencije za Nekretnine', tr:'Emlak Firmaları', en:'Real Estate Companies', de:'Immobilienfirmen', fr:'Agences immobilières', it:'Agenzie immobiliari', bs:'Agencije za Nekretnine', el:'Εταιρείες Ακινήτων', ru:'Агентства недвижимости'},
  gallery_empty: {sq:'Ende asnjë biznes në këtë kategori.', sr:'Još uvek nema preduzeća u ovoj kategoriji.', tr:'Bu kategoride henüz işletme yok.', en:'No businesses in this category yet.', de:'Noch keine Unternehmen in dieser Kategorie.', fr:'Aucune entreprise dans cette catégorie pour l\'instant.', it:'Nessuna azienda in questa categoria ancora.', bs:'Još uvijek nema preduzeća u ovoj kategoriji.', el:'Δεν υπάρχουν ακόμη επιχειρήσεις σε αυτή την κατηγορία.', ru:'В этой категории пока нет компаний.'},
  gallery_view_listings: {sq:'Shiko Shpalljet', sr:'Pogledaj Oglase', tr:'İlanları Gör', en:'View Listings', de:'Anzeigen ansehen', fr:'Voir les annonces', it:'Vedi annunci', bs:'Pogledaj Oglase', el:'Προβολή Αγγελιών', ru:'Смотреть объявления'},

  stats_active_listings: {sq:'Shpallje të Verifikuara', sr:'Verifikovani Oglasi', tr:'Doğrulanmış İlan', en:'Verified Listings', de:'Verifizierte Anzeigen', fr:'Annonces vérifiées', it:'Annunci verificati', bs:'Verifikovani Oglasi', el:'Επαληθευμένες Αγγελίες', ru:'Проверенные объявления'},
  stats_active_users: {sq:'Përdorues Aktivë', sr:'Aktivni Korisnici', tr:'Aktif Kullanıcı', en:'Active Users', de:'Aktive Nutzer', fr:'Utilisateurs actifs', it:'Utenti attivi', bs:'Aktivni Korisnici', el:'Ενεργοί Χρήστες', ru:'Активные пользователи'},
  stats_cities_covered: {sq:'Qytete të Mbuluara', sr:'Pokrivenih Gradova', tr:'Kapsanan Şehir', en:'Cities Covered', de:'Abgedeckte Städte', fr:'Villes couvertes', it:'Città coperte', bs:'Pokrivenih Gradova', el:'Πόλεις που Καλύπτονται', ru:'Охваченные города'},

  testimonials_title: {sq:'Çfarë Thonë Përdoruesit Tanë', sr:'Šta Kažu Naši Korisnici', tr:'Kullanıcılarımız Ne Diyor', en:'What Our Users Say', de:'Was unsere Nutzer sagen', fr:'Ce que disent nos utilisateurs', it:'Cosa dicono i nostri utenti', bs:'Šta Kažu Naši Korisnici', el:'Τι Λένε οι Χρήστες μας', ru:'Что говорят наши пользователи'},
  testimonials_empty: {sq:'Ende asnjë vlerësim — bëhu i pari që ndan përvojën tënde.', sr:'Još uvek nema recenzija — budite prvi koji deli svoje iskustvo.', tr:'Henüz yorum yok — deneyiminizi paylaşan ilk kişi olun.', en:'No reviews yet — be the first to share your experience.', de:'Noch keine Bewertungen — seien Sie der Erste, der seine Erfahrung teilt.', fr:'Aucun avis pour l\'instant — soyez le premier à partager votre expérience.', it:'Nessuna recensione ancora — sii il primo a condividere la tua esperienza.', bs:'Još uvijek nema recenzija — budite prvi koji dijeli svoje iskustvo.', el:'Δεν υπάρχουν ακόμη κριτικές — γίνετε ο πρώτος που θα μοιραστεί την εμπειρία του.', ru:'Пока нет отзывов — станьте первым, кто поделится опытом.'},
  btn_leave_review: {sq:'Lini një Vlerësim', sr:'Ostavite Recenziju', tr:'Yorum Bırak', en:'Leave a Review', de:'Bewertung abgeben', fr:'Laisser un avis', it:'Lascia una recensione', bs:'Ostavite Recenziju', el:'Αφήστε μια Κριτική', ru:'Оставить отзыв'},
  label_your_review: {sq:'Vlerësimi juaj', sr:'Vaša recenzija', tr:'Yorumunuz', en:'Your review', de:'Ihre Bewertung', fr:'Votre avis', it:'La tua recensione', bs:'Vaša recenzija', el:'Η κριτική σας', ru:'Ваш отзыв'},
  label_rating: {sq:'Vlerësimi', sr:'Ocena', tr:'Puan', en:'Rating', de:'Bewertung', fr:'Note', it:'Valutazione', bs:'Ocjena', el:'Βαθμολογία', ru:'Оценка'},
  toast_review_submitted: {sq:'Faleminderit! Vlerësimi juaj do të shfaqet pas miratimit.', sr:'Hvala! Vaša recenzija će se pojaviti nakon odobrenja.', tr:'Teşekkürler! Yorumunuz onaylandıktan sonra görünecek.', en:'Thank you! Your review will appear after approval.', de:'Danke! Ihre Bewertung wird nach Freigabe angezeigt.', fr:'Merci ! Votre avis apparaîtra après approbation.', it:'Grazie! La tua recensione apparirà dopo l\'approvazione.', bs:'Hvala! Vaša recenzija će se pojaviti nakon odobrenja.', el:'Ευχαριστούμε! Η κριτική σας θα εμφανιστεί μετά την έγκριση.', ru:'Спасибо! Ваш отзыв появится после одобрения.'},

  nav_blog: {sq:'Blog', sr:'Blog', tr:'Blog', en:'Blog', de:'Blog', fr:'Blog', it:'Blog', bs:'Blog', el:'Blog', ru:'Блог'},
  blog_title: {sq:'Blog', sr:'Blog', tr:'Blog', en:'Blog', de:'Blog', fr:'Blog', it:'Blog', bs:'Blog', el:'Blog', ru:'Блог'},
  blog_empty: {sq:'Ende asnjë artikull.', sr:'Još uvek nema članaka.', tr:'Henüz makale yok.', en:'No posts yet.', de:'Noch keine Beiträge.', fr:'Aucun article pour l\'instant.', it:'Nessun articolo ancora.', bs:'Još uvijek nema članaka.', el:'Δεν υπάρχουν ακόμη άρθρα.', ru:'Пока нет статей.'},
  blog_read_more: {sq:'Lexo më shumë', sr:'Pročitaj više', tr:'Devamını oku', en:'Read more', de:'Weiterlesen', fr:'Lire la suite', it:'Leggi di più', bs:'Pročitaj više', el:'Διαβάστε περισσότερα', ru:'Читать далее'},
  blog_back: {sq:'Kthehu te Blogu', sr:'Nazad na Blog', tr:'Blog\'a Dön', en:'Back to Blog', de:'Zurück zum Blog', fr:'Retour au blog', it:'Torna al blog', bs:'Nazad na Blog', el:'Επιστροφή στο Blog', ru:'Назад в блог'},

  nav_help: {sq:'Qendra e Ndihmës', sr:'Centar za Pomoć', tr:'Yardım Merkezi', en:'Help Center', de:'Hilfe-Center', fr:'Centre d\'aide', it:'Centro assistenza', bs:'Centar za Pomoć', el:'Κέντρο Βοήθειας', ru:'Центр помощи'},
  help_title: {sq:'Qendra e Ndihmës', sr:'Centar za Pomoć', tr:'Yardım Merkezi', en:'Help Center', de:'Hilfe-Center', fr:'Centre d\'aide', it:'Centro assistenza', bs:'Centar za Pomoć', el:'Κέντρο Βοήθειας', ru:'Центр помощи'},

  label_brand: {sq:'Marka', sr:'Marka', tr:'Marka', en:'Brand', de:'Marke', fr:'Marque', it:'Marca', bs:'Marka', el:'Μάρκα', ru:'Марка'},
  filter_all_brands: {sq:'Të gjitha markat', sr:'Sve marke', tr:'Tüm markalar', en:'All brands', de:'Alle Marken', fr:'Toutes les marques', it:'Tutte le marche', bs:'Sve marke', el:'Όλες οι μάρκες', ru:'Все марки'},
  toast_listing_limit_reached: {sq:'Keni arritur limitin e shpalljeve për planin tuaj. Përmirësoni planin ose blini një kredit në faqen Paketat.', sr:'Dostigli ste limit oglasa za vaš plan. Nadogradite plan ili kupite kredit na stranici Paketi.', tr:'Planınızın ilan limitine ulaştınız. Paketler sayfasından planınızı yükseltin veya kredi satın alın.', en:'You\'ve reached your plan\'s listing limit. Upgrade your plan or buy a credit on the Packages page.', de:'Sie haben das Anzeigenlimit Ihres Plans erreicht. Erweitern Sie Ihren Plan oder kaufen Sie ein Guthaben auf der Pakete-Seite.', fr:'Vous avez atteint la limite d\'annonces de votre forfait. Améliorez votre forfait ou achetez un crédit sur la page Forfaits.', it:'Hai raggiunto il limite di annunci del tuo piano. Aggiorna il piano o acquista un credito nella pagina Pacchetti.', bs:'Dostigli ste limit oglasa za vaš plan. Nadogradite plan ili kupite kredit na stranici Paketi.', el:'Φτάσατε το όριο αγγελιών του πλάνου σας. Αναβαθμίστε το πλάνο ή αγοράστε πίστωση στη σελίδα Πακέτα.', ru:'Вы достигли лимита объявлений по вашему плану. Улучшите план или купите кредит на странице Пакеты.'},
  admin_tab_testimonials: {sq:'Vlerësimet', sr:'Recenzije', tr:'Yorumlar', en:'Testimonials', de:'Bewertungen', fr:'Avis', it:'Recensioni', bs:'Recenzije', el:'Κριτικές', ru:'Отзывы'},
  admin_no_testimonials: {sq:'Ende asnjë vlerësim.', sr:'Još uvek nema recenzija.', tr:'Henüz yorum yok.', en:'No testimonials yet.', de:'Noch keine Bewertungen.', fr:'Aucun avis pour l\'instant.', it:'Nessuna recensione ancora.', bs:'Još uvijek nema recenzija.', el:'Δεν υπάρχουν ακόμη κριτικές.', ru:'Пока нет отзывов.'},
  admin_col_approved: {sq:'Miratuar', sr:'Odobreno', tr:'Onaylı', en:'Approved', de:'Genehmigt', fr:'Approuvé', it:'Approvato', bs:'Odobreno', el:'Εγκρίθηκε', ru:'Одобрено'},
  btn_approve: {sq:'Miro', sr:'Odobri', tr:'Onayla', en:'Approve', de:'Genehmigen', fr:'Approuver', it:'Approva', bs:'Odobri', el:'Έγκριση', ru:'Одобрить'},
  label_post_title: {sq:'Titulli', sr:'Naslov', tr:'Başlık', en:'Title', de:'Titel', fr:'Titre', it:'Titolo', bs:'Naslov', el:'Τίτλος', ru:'Заголовок'},
  label_post_excerpt: {sq:'Përmbledhje (opsionale)', sr:'Sažetak (opciono)', tr:'Özet (opsiyonel)', en:'Excerpt (optional)', de:'Zusammenfassung (optional)', fr:'Extrait (facultatif)', it:'Riassunto (facoltativo)', bs:'Sažetak (opciono)', el:'Περίληψη (προαιρετικό)', ru:'Отрывок (необязательно)'},
  label_post_content: {sq:'Përmbajtja', sr:'Sadržaj', tr:'İçerik', en:'Content', de:'Inhalt', fr:'Contenu', it:'Contenuto', bs:'Sadržaj', el:'Περιεχόμενο', ru:'Содержание'},
  label_cover_image: {sq:'URL i fotos kryesore (opsionale)', sr:'URL naslovne slike (opciono)', tr:'Kapak görseli URL (opsiyonel)', en:'Cover image URL (optional)', de:'URL des Titelbilds (optional)', fr:'URL de l\'image de couverture (facultatif)', it:'URL immagine di copertina (facoltativo)', bs:'URL naslovne slike (opciono)', el:'URL εικόνας εξωφύλλου (προαιρετικό)', ru:'URL обложки (необязательно)'},
  btn_publish_post: {sq:'Publiko Artikullin', sr:'Objavi Članak', tr:'Makaleyi Yayınla', en:'Publish Post', de:'Beitrag veröffentlichen', fr:'Publier l\'article', it:'Pubblica articolo', bs:'Objavi Članak', el:'Δημοσίευση Άρθρου', ru:'Опубликовать статью'},

  nav_account: {sq:'Llogaria Ime', sr:'Moj Nalog', tr:'Hesabım', en:'My Account', de:'Mein Konto', fr:'Mon compte', it:'Il mio account', bs:'Moj Nalog', el:'Ο Λογαριασμός μου', ru:'Мой аккаунт'},
  account_title: {sq:'Llogaria Ime', sr:'Moj Nalog', tr:'Hesabım', en:'My Account', de:'Mein Konto', fr:'Mon compte', it:'Il mio account', bs:'Moj Nalog', el:'Ο Λογαριασμός μου', ru:'Мой аккаунт'},
  account_email_label: {sq:'Email', sr:'Email', tr:'E-posta', en:'Email', de:'E-Mail', fr:'E-mail', it:'Email', bs:'Email', el:'Email', ru:'Эл. почта'},
  account_type_label: {sq:'Lloji i llogarisë', sr:'Tip naloga', tr:'Hesap Türü', en:'Account Type', de:'Kontotyp', fr:'Type de compte', it:'Tipo di account', bs:'Tip naloga', el:'Τύπος Λογαριασμού', ru:'Тип аккаунта'},
  account_type_individual: {sq:'Individual', sr:'Fizičko lice', tr:'Bireysel', en:'Individual', de:'Privatperson', fr:'Particulier', it:'Privato', bs:'Fizičko lice', el:'Ιδιώτης', ru:'Физическое лицо'},
  account_view_all: {sq:'Shiko të gjitha', sr:'Pogledaj sve', tr:'Tümünü Gör', en:'View all', de:'Alle ansehen', fr:'Tout voir', it:'Vedi tutti', bs:'Pogledaj sve', el:'Προβολή όλων', ru:'Смотреть все'},
  phone_locked_message: {sq:'Duhet të hyni në llogari për të parë numrin e telefonit.', sr:'Morate se prijaviti da biste videli broj telefona.', tr:'Telefon numarasını görmek için üye girişi yapmalısınız.', en:'You must log in to see the phone number.', de:'Sie müssen sich anmelden, um die Telefonnummer zu sehen.', fr:'Vous devez vous connecter pour voir le numéro de téléphone.', it:'Devi accedere per vedere il numero di telefono.', bs:'Morate se prijaviti da biste vidjeli broj telefona.', el:'Πρέπει να συνδεθείτε για να δείτε τον αριθμό τηλεφώνου.', ru:'Чтобы увидеть номер телефона, войдите в аккаунт.'},
  phone_locked_cta: {sq:'Hyr për ta parë', sr:'Prijavite se da vidite', tr:'Görmek için giriş yap', en:'Log in to view', de:'Zum Anzeigen anmelden', fr:'Connectez-vous pour voir', it:'Accedi per vedere', bs:'Prijavite se da vidite', el:'Συνδεθείτε για προβολή', ru:'Войдите, чтобы увидеть'}
};

export const CAT_I18N: Record<string, { name: Record<LangCode,string>; desc: Record<LangCode,string> }> = {
  emlak: {
    name: {sq:'Prona', sr:'Nekretnine', tr:'Emlak', en:'Real Estate', de:'Immobilien', fr:'Immobilier', it:'Immobili', bs:'Nekretnine', el:'Ακίνητα', ru:'Недвижимость'},
    desc: {sq:'Banesa dhe lokale me shitje dhe qira', sr:'Stanovi i poslovni prostori za prodaju i izdavanje', tr:'Satılık ve kiralık konut, iş yeri', en:'Homes and business premises for sale and rent', de:'Wohnungen und Gewerbeflächen zum Kauf und zur Miete', fr:'Logements et locaux commerciaux à vendre et à louer', it:'Case e locali commerciali in vendita e affitto', bs:'Stanovi i poslovni prostori za prodaju i iznajmljivanje', el:'Κατοικίες και επαγγελματικοί χώροι προς πώληση και ενοικίαση', ru:'Жильё и коммерческие помещения на продажу и в аренду'}
  },
  vasita: {
    name: {sq:'Automjete', sr:'Vozila', tr:'Vasıta', en:'Vehicles', de:'Fahrzeuge', fr:'Véhicules', it:'Veicoli', bs:'Vozila', el:'Οχήματα', ru:'Транспорт'},
    desc: {sq:'Shpallje automjetesh të reja dhe të përdorura', sr:'Oglasi novih i polovnih vozila', tr:'İkinci el ve sıfır araç ilanları', en:'New and used vehicle listings', de:'Anzeigen für neue und gebrauchte Fahrzeuge', fr:'Annonces de véhicules neufs et d\'occasion', it:'Annunci di veicoli nuovi e usati', bs:'Oglasi novih i polovnih vozila', el:'Αγγελίες καινούργιων και μεταχειρισμένων οχημάτων', ru:'Объявления о новых и подержанных автомобилях'}
  },
  esya: {
    name: {sq:'Sende të Përdorura', sr:'Polovna Roba', tr:'İkinci El Eşya', en:'Second-Hand Goods', de:'Gebrauchtwaren', fr:'Articles d\'occasion', it:'Articoli usati', bs:'Polovna Roba', el:'Μεταχειρισμένα Είδη', ru:'Товары с рук'},
    desc: {sq:'Elektronikë, mobilje, artikuj shtëpiakë', sr:'Elektronika, nameštaj, kućni predmeti', tr:'Elektronik, mobilya, ev eşyası', en:'Electronics, furniture, household items', de:'Elektronik, Möbel, Haushaltsgegenstände', fr:'Électronique, meubles, articles ménagers', it:'Elettronica, mobili, articoli per la casa', bs:'Elektronika, namještaj, kućni predmeti', el:'Ηλεκτρονικά, έπιπλα, οικιακά είδη', ru:'Электроника, мебель, товары для дома'}
  }
};

export const SUB_I18N: Record<string, Record<LangCode,string>> = {
  'satilik-daire': {sq:'Banesë në shitje', sr:'Stan na prodaju', tr:'Satılık Daire', en:'Apartment for Sale', de:'Wohnung zu verkaufen', fr:'Appartement à vendre', it:'Appartamento in vendita', bs:'Stan na prodaju', el:'Διαμέρισμα προς πώληση', ru:'Квартира на продажу'},
  'kiralik-daire': {sq:'Banesë me qira', sr:'Stan za izdavanje', tr:'Kiralık Daire', en:'Apartment for Rent', de:'Wohnung zu vermieten', fr:'Appartement à louer', it:'Appartamento in affitto', bs:'Stan za iznajmljivanje', el:'Διαμέρισμα προς ενοικίαση', ru:'Квартира в аренду'},
  'satilik-isyeri': {sq:'Lokal në shitje', sr:'Poslovni prostor na prodaju', tr:'Satılık İş Yeri', en:'Business Premises for Sale', de:'Gewerbefläche zu verkaufen', fr:'Local commercial à vendre', it:'Locale commerciale in vendita', bs:'Poslovni prostor na prodaju', el:'Επαγγελματικός χώρος προς πώληση', ru:'Коммерческое помещение на продажу'},
  'kiralik-isyeri': {sq:'Lokal me qira', sr:'Poslovni prostor za izdavanje', tr:'Kiralık İş Yeri', en:'Business Premises for Rent', de:'Gewerbefläche zu vermieten', fr:'Local commercial à louer', it:'Locale commerciale in affitto', bs:'Poslovni prostor za iznajmljivanje', el:'Επαγγελματικός χώρος προς ενοικίαση', ru:'Коммерческое помещение в аренду'},
  'arsa': {sq:'Tokë', sr:'Plac', tr:'Arsa', en:'Land', de:'Grundstück', fr:'Terrain', it:'Terreno', bs:'Plac', el:'Οικόπεδο', ru:'Земельный участок'},
  'otomobil': {sq:'Automobil', sr:'Automobil', tr:'Otomobil', en:'Car', de:'Auto', fr:'Voiture', it:'Automobile', bs:'Automobil', el:'Αυτοκίνητο', ru:'Автомобиль'},
  'arazi-suv': {sq:'Xhip / SUV', sr:'Terenac / SUV', tr:'Arazi Aracı / SUV', en:'Off-road / SUV', de:'Geländewagen / SUV', fr:'Tout-terrain / SUV', it:'Fuoristrada / SUV', bs:'Terenac / SUV', el:'SUV', ru:'Внедорожник / SUV'},
  'motosiklet': {sq:'Motoçikletë', sr:'Motocikl', tr:'Motosiklet', en:'Motorcycle', de:'Motorrad', fr:'Moto', it:'Motocicletta', bs:'Motocikl', el:'Μοτοσικλέτα', ru:'Мотоцикл'},
  'ticari': {sq:'Automjet Komercial', sr:'Komercijalno Vozilo', tr:'Ticari Araç', en:'Commercial Vehicle', de:'Nutzfahrzeug', fr:'Véhicule utilitaire', it:'Veicolo commerciale', bs:'Komercijalno Vozilo', el:'Επαγγελματικό Όχημα', ru:'Коммерческий транспорт'},
  'elektronik': {sq:'Elektronikë', sr:'Elektronika', tr:'Elektronik', en:'Electronics', de:'Elektronik', fr:'Électronique', it:'Elettronica', bs:'Elektronika', el:'Ηλεκτρονικά', ru:'Электроника'},
  'mobilya': {sq:'Mobilje', sr:'Nameštaj', tr:'Mobilya', en:'Furniture', de:'Möbel', fr:'Meubles', it:'Mobili', bs:'Namještaj', el:'Έπιπλα', ru:'Мебель'},
  'giyim': {sq:'Veshje', sr:'Odeća', tr:'Giyim', en:'Clothing', de:'Kleidung', fr:'Vêtements', it:'Abbigliamento', bs:'Odjeća', el:'Ρούχα', ru:'Одежда'},
  'diger': {sq:'Tjetër', sr:'Ostalo', tr:'Diğer', en:'Other', de:'Sonstiges', fr:'Autre', it:'Altro', bs:'Ostalo', el:'Άλλο', ru:'Другое'}
};

export function t(key: keyof typeof UI, lang: LangCode): string {
  const entry = UI[key] as Record<string, string> | undefined;
  if (!entry) return key;
  return entry[lang] || entry.en || key;
}
export function catName(id: string, lang: LangCode): string {
  const c = CAT_I18N[id];
  return c.name[lang] || c.name.en;
}
export function catDesc(id: string, lang: LangCode): string {
  const c = CAT_I18N[id];
  return c.desc[lang] || c.desc.en;
}
export function subName(id: string, lang: LangCode): string {
  const s = SUB_I18N[id];
  return s[lang] || s.en;
}
